const BASE=location.pathname.startsWith('/Zero-trust/')?'/Zero-trust/':'/';
let TOOLS=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=t=>`<a class="tool-card" href="${BASE}tools/${t.slug}/"><span class="eyebrow">${esc(t.categoryName)}</span><h3>${esc(t.name)}</h3><p>Real browser tool · ${t.phase===1?'local-first':'network-dependent'}</p></a>`;
function wireTheme(){const b=document.querySelector('#themeBtn');if(!b)return;const key='zt-theme';const apply=v=>{document.body.classList.toggle('dark',v==='dark');b.textContent=v==='dark'?'Light':'Dark'};apply(localStorage.getItem(key)||'light');b.onclick=()=>{const v=document.body.classList.contains('dark')?'light':'dark';localStorage.setItem(key,v);apply(v)}}
function wireMenu(){const b=document.querySelector('#menuBtn'),m=document.querySelector('#mobileNav');if(b&&m)b.onclick=()=>{const open=m.hidden;m.hidden=!open;b.setAttribute('aria-expanded',String(open))}}
async function loadTools(){try{const r=await fetch(`${BASE}data/tools-index.json`,{cache:'force-cache'});if(!r.ok)throw Error('catalog unavailable');TOOLS=await r.json();window.ZT_TOOLS=TOOLS}catch(e){console.error(e);window.ZT_TOOLS=[]}}
function boot(){wireTheme();wireMenu();const f=document.querySelector('#featured');if(f)f.innerHTML=TOOLS.slice(0,12).map(card).join('');const a=document.querySelector('#allTools'),q=document.querySelector('#toolSearch'),cat=document.querySelector('#categoryFilter');if(a){const draw=()=>{const s=(q?.value||'').trim().toLowerCase(),c=cat?.value||'';const items=TOOLS.filter(t=>(!s||`${t.name} ${t.categoryName} ${t.slug}`.toLowerCase().includes(s))&&(!c||t.category===c));a.innerHTML=items.map(card).join('');const n=document.querySelector('#toolCount');if(n)n.textContent=`${items.length} tools`};q?.addEventListener('input',draw);cat?.addEventListener('change',draw);draw()}}
document.addEventListener('DOMContentLoaded',async()=>{await loadTools();boot()});
