const BASE=location.pathname.startsWith('/Zero-trust/')?'/Zero-trust/':'/';
let TOOLS=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=t=>`<a class="tool-card" href="${BASE}tools/${t.slug}/"><span class="eyebrow">${esc(t.categoryName)}</span><h3>${esc(t.name)}</h3><p>Real browser tool · ${t.phase===1?'local-first':'network-dependent'}</p></a>`;
function injectResponsiveNav(){if(document.getElementById('zt-nav-responsive'))return;const s=document.createElement('style');s.id='zt-nav-responsive';s.textContent=`@media(max-width:1100px){nav>.desktop-quick,nav>.nav-all,nav>.nav-security{display:none!important}nav>.mobile-menu{display:inline-flex!important;align-items:center;justify-content:center;min-width:50px;min-height:44px;padding:9px 12px;font-weight:750}.mobile-panel{position:fixed!important;left:12px!important;right:12px!important;top:76px!important;width:auto!important;max-height:calc(100vh - 90px)!important;overflow:auto!important;z-index:120}.quick-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:760px){.quick-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.category-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.site-header{padding-left:12px!important;padding-right:12px!important}.brand-name{font-size:15px}.quick-grid{grid-template-columns:1fr 1fr}.mobile-menu{min-width:48px!important}.menu-label{display:none}}`;document.head.appendChild(s)}
function wireTheme(){const b=document.querySelector('#themeBtn');if(!b)return;const key='zt-theme';const apply=v=>{document.body.classList.toggle('dark',v==='dark');b.textContent=v==='dark'?'Light':'Dark';b.setAttribute('aria-label',v==='dark'?'Switch to light theme':'Switch to dark theme')};apply(localStorage.getItem(key)||'light');b.onclick=()=>{const v=document.body.classList.contains('dark')?'light':'dark';localStorage.setItem(key,v);apply(v)}}
function wireMenu(){const b=document.querySelector('#menuBtn'),m=document.querySelector('#mobileNav');if(!b||!m)return;const close=()=>{m.hidden=true;m.style.display='none';m.removeAttribute('data-open');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open tools menu');b.querySelector('.menu-label')?.replaceChildren(document.createTextNode('Menu'));document.body.classList.remove('menu-open')};const open=()=>{m.hidden=false;m.style.removeProperty('display');m.setAttribute('data-open','');b.setAttribute('aria-expanded','true');b.setAttribute('aria-label','Close tools menu');b.querySelector('.menu-label')?.replaceChildren(document.createTextNode('Close'));document.body.classList.add('menu-open')};close();b.onclick=e=>{e.stopPropagation();m.hidden?open():close()};m.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.addEventListener('click',e=>{if(!m.hidden&&!m.contains(e.target)&&!b.contains(e.target))close()});window.addEventListener('resize',()=>{if(window.innerWidth>1100)close()},{passive:true})}
async function loadTools(){try{const r=await fetch(`${BASE}data/tools-index.json`,{cache:'force-cache'});if(!r.ok)throw Error('catalog unavailable');TOOLS=await r.json();window.ZT_TOOLS=TOOLS}catch(e){console.error(e);window.ZT_TOOLS=[]}}
function boot(){injectResponsiveNav();wireTheme();wireMenu();const f=document.querySelector('#featured');if(f&&TOOLS.length)f.innerHTML=TOOLS.slice(0,12).map(card).join('');const a=document.querySelector('#allTools'),q=document.querySelector('#toolSearch'),cat=document.querySelector('#categoryFilter');if(a){const draw=()=>{const s=(q?.value||'').trim().toLowerCase(),c=cat?.value||'';const items=TOOLS.filter(t=>(!s||`${t.name} ${t.categoryName} ${t.slug}`.toLowerCase().includes(s))&&(!c||t.category===c));a.innerHTML=items.map(card).join('');const n=document.querySelector('#toolCount');if(n)n.textContent=`${items.length} tools`};q?.addEventListener('input',draw);cat?.addEventListener('change',draw);draw()}}
document.addEventListener('DOMContentLoaded',async()=>{await loadTools();boot()});
