const num=v=>{const n=Number(String(v??'').replace(/[₹,$,%\s]/g,''));if(!Number.isFinite(n))throw Error('Enter valid numeric inputs.');return n};
const safe=(n)=>Number.isFinite(n)?Math.round((n+Number.EPSILON)*1e10)/1e10:0;
export const sip=(p,r,y)=>{p=num(p);r=num(r)/1200;y=num(y);if(p<0||r<0||y<0)throw Error('Inputs cannot be negative.');const n=Math.round(y*12);return safe(r===0?p*n:p*((Math.pow(1+r,n)-1)/r)*(1+r))};
export const emi=(p,r,y)=>{p=num(p);r=num(r)/1200;y=num(y);const n=Math.round(y*12);if(p<0||r<0||n<=0)throw Error('Enter valid principal, rate and tenure.');return safe(r===0?p/n:p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1))};
export const compound=(p,r,t,n=1)=>{p=num(p);r=num(r)/100;t=num(t);n=num(n);if(p<0||t<0||n<=0)throw Error('Enter valid inputs.');return safe(p*Math.pow(1+r/n,n*t))};
export const ppf=(p,r=7.1,y=15)=>{p=num(p);r=num(r)/100;y=num(y);if(p<0||y<0)throw Error('Enter valid inputs.');let v=0;for(let i=0;i<y;i++)v=(v+p)*(1+r);return safe(v)};
export const gst=(amount,rate)=>{const a=num(amount),r=num(rate)/100;if(a<0||r<0)throw Error('Enter valid inputs.');return{tax:safe(a*r),total:safe(a*(1+r)),base:a}};
export const cagr=(start,end,years)=>{const a=num(start),b=num(end),y=num(years);if(a<=0||b<0||y<=0)throw Error('Start and years must be positive.');return safe((Math.pow(b/a,1/y)-1)*100)};
export const nps=(p,r,y)=>{p=num(p);r=num(r)/1200;y=num(y);const n=Math.round(y*12);if(p<0||r<0||n<=0)throw Error('Enter valid inputs.');return safe(r===0?p*n:p*(Math.pow(1+r,n)-1)/r)};
export const bmi=(kg,m)=>{const w=num(kg),h=num(m);if(w<=0||h<=0)throw Error('Weight and height must be positive.');return safe(w/(h*h))};
export const bmr=(kg,cm,age,sex='male')=>{const w=num(kg),h=num(cm),a=num(age);if(w<=0||h<=0||a<=0)throw Error('Enter valid inputs.');return safe(10*w+6.25*h-5*a+(String(sex).toLowerCase().startsWith('f')?-161:5))};
export const calorieDeficit=(maintenance,target)=>{const a=num(maintenance),b=num(target);if(a<0||b<0)throw Error('Calories cannot be negative.');return safe(a-b)};
const MAP={sip,emi,ppf,compound,gst,cagr,nps,bmi,bmr,'calorie-deficit':calorieDeficit};
export function mount(slug){const key=Object.keys(MAP).find(k=>slug.toLowerCase().includes(k));if(!key)throw Error(`No calculator formula mapped for ${slug}.`);const app=document.querySelector('#toolApp');app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST · deterministic calculator</div><div class="control-grid"><label>Input 1<input id="ca" type="text" inputmode="decimal"></label><label>Input 2<input id="cb" type="text" inputmode="decimal"></label><label>Input 3<input id="cc" type="text" inputmode="decimal"></label></div><button class="btn primary" id="cr">Calculate</button><div class="output" id="co">Ready.</div></div>`;document.querySelector('#cr').onclick=()=>{try{const a=['sip','emi','compound','nps'].includes(key)?sip:MAP[key];let r;if(key==='gst')r=a(document.querySelector('#ca').value,document.querySelector('#cb').value).total;else if(key==='bmi')r=a(document.querySelector('#ca').value,document.querySelector('#cb').value);else if(key==='bmr')r=a(document.querySelector('#ca').value,document.querySelector('#cb').value,document.querySelector('#cc').value);else if(key==='calorie-deficit')r=a(document.querySelector('#ca').value,document.querySelector('#cb').value);else r=a(document.querySelector('#ca').value,document.querySelector('#cb').value,document.querySelector('#cc').value);document.querySelector('#co').textContent=String(r);document.querySelector('#co').className='output success'}catch(e){document.querySelector('#co').textContent=e.message;document.querySelector('#co').className='output error'}}}
