const $=s=>document.querySelector(s);const clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n));const num=v=>{const n=Number(v);if(!Number.isFinite(n))throw Error('Enter valid numeric values.');return n};
export function hexToRgb(hex){let h=String(hex).trim().replace(/^#/,'');if(/^[0-9a-f]{3}$/i.test(h))h=h.split('').map(x=>x+x).join('');if(!/^[0-9a-f]{6}$/i.test(h))throw Error('HEX must be 3 or 6 hexadecimal digits.');return{r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)}}
export function rgbToHex(r,g,b){return '#'+[r,g,b].map(x=>Math.round(clamp(num(x),0,255)).toString(16).padStart(2,'0')).join('').toUpperCase()}
export function rgbToHsl(r,g,b){r=clamp(num(r)/255);g=clamp(num(g)/255);b=clamp(num(b)/255);const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn,l=(mx+mn)/2;let h=0,s=0;if(d){s=d/(1-Math.abs(2*l-1));switch(mx){case r:h=((g-b)/d+(g<b?6:0))/6;break;case g:h=((b-r)/d+2)/6;break;default:h=((r-g)/d+4)/6}}return{h:h*360,s:s*100,l:l*100}}
export function hslToRgb(h,s,l){h=((num(h)%360)+360)%360/360;s=clamp(num(s)/100);l=clamp(num(l)/100);const f=n=>{const k=(n+h*12)%12,a=s*Math.min(l,1-l),c=l-a*Math.max(-1,Math.min(k-3,9-k,1));return Math.round(255*c)};return{r:f(0),g:f(8),b:f(4)}}
export function rgbToHsv(r,g,b){r=clamp(num(r)/255);g=clamp(num(g)/255);b=clamp(num(b)/255);const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;if(d){if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return{h,s:mx?d/mx*100:0,v:mx*100}}
export function hsvToRgb(h,s,v){h=((num(h)%360)+360)%360;s=clamp(num(s)/100);v=clamp(num(v)/100);const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return{r:Math.round((r+m)*255),g:Math.round((g+m)*255),b:Math.round((b+m)*255)}}
export function rgbToCmyk(r,g,b){r=clamp(num(r)/255);g=clamp(num(g)/255);b=clamp(num(b)/255);const k=1-Math.max(r,g,b);if(k>=.999)return{c:0,m:0,y:0,k:100};return{c:(1-r-k)/(1-k)*100,m:(1-g-k)/(1-k)*100,y:(1-b-k)/(1-k)*100,k:k*100}}
export function cmykToRgb(c,m,y,k){c=clamp(num(c)/100);m=clamp(num(m)/100);y=clamp(num(y)/100);k=clamp(num(k)/100);return{r:Math.round(255*(1-c)*(1-k)),g:Math.round(255*(1-m)*(1-k)),b:Math.round(255*(1-y)*(1-k))}}
export function relativeLuminance(r,g,b){const f=x=>{x=clamp(num(x)/255);return x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4)};return .2126*f(r)+.7152*f(g)+.0722*f(b)}
export function contrastRatio(a,b){const x=typeof a==='string'?hexToRgb(a):a,y=typeof b==='string'?hexToRgb(b):b,l1=relativeLuminance(x.r,x.g,x.b),l2=relativeLuminance(y.r,y.g,y.b);return(Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)}
const fmt=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,Math.round(v*10000)/10000]));
export function convert(input,from,to){let rgb;if(from==='hex')rgb=hexToRgb(input);else if(from==='rgb')rgb=input;else if(from==='hsl')rgb=hslToRgb(input.h,input.s,input.l);else if(from==='hsv')rgb=hsvToRgb(input.h,input.s,input.v);else if(from==='cmyk')rgb=cmykToRgb(input.c,input.m,input.y,input.k);else throw Error('Unsupported source color model.');if(to==='rgb')return fmt(rgb);if(to==='hex')return rgbToHex(rgb.r,rgb.g,rgb.b);if(to==='hsl')return fmt(rgbToHsl(rgb.r,rgb.g,rgb.b));if(to==='hsv')return fmt(rgbToHsv(rgb.r,rgb.g,rgb.b));if(to==='cmyk')return fmt(rgbToCmyk(rgb.r,rgb.g,rgb.b));throw Error('Unsupported target color model.')}
export function mount(slug){const app=$('#toolApp');if(!app)return;const contrast=/contrast|wcag|accessibility/.test(slug.toLowerCase());app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST · color conversion and WCAG 2.1</div><div class="control-grid"><label>HEX A<input id="ca" value="#3366CC"></label><label>HEX B<input id="cb" value="#FFFFFF"></label></div><button class="btn primary" id="cc">${contrast?'Evaluate contrast':'Convert'}</button><div class="output" id="co">Ready.</div></div>`;$('#cc').onclick=()=>{try{if(contrast){const ratio=contrastRatio($('#ca').value,$('#cb').value);$('#co').textContent=JSON.stringify({ratio:Number(ratio.toFixed(2)),normalTextAA:ratio>=4.5,normalTextAAA:ratio>=7,largeTextAA:ratio>=3,largeTextAAA:ratio>=4.5},null,2)}else{const rgb=hexToRgb($('#ca').value);$('#co').textContent=JSON.stringify({hex:rgbToHex(rgb.r,rgb.g,rgb.b),rgb,hsl:fmt(rgbToHsl(rgb.r,rgb.g,rgb.b)),hsv:fmt(rgbToHsv(rgb.r,rgb.g,rgb.b)),cmyk:fmt(rgbToCmyk(rgb.r,rgb.g,rgb.b))},null,2)}$('#co').className='output success'}catch(e){$('#co').textContent=e.message;$('#co').className='output error'}}}
