/* Deterministic local data transformation engine. No server upload and no external API dependency. */
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const shell=app=>{app.innerHTML='<div class="zt-card"><div class="zt-local">LOCAL-FIRST PROCESSING — data stays in this browser</div><div class="zt-input"></div><div class="zt-actions tool-actions"></div><div class="zt-output output" aria-live="polite">Ready.</div></div>';return{input:app.querySelector('.zt-input'),actions:app.querySelector('.zt-actions'),out:app.querySelector('.zt-output')}};
const text=s=>String(s??'');
const csvParse=s=>{const rows=[],row=[];let cur='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'&&s[i+1]==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if((c===','||c==='\t')&&!q){row.push(cur);cur='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cur);rows.push(row.splice(0));cur='';continue}cur+=c}if(cur!==''||row.length) {row.push(cur);rows.push(row)}return rows.filter(r=>r.some(v=>String(v).trim()!==''))};
const csvCell=v=>{const s=text(v);return /[",\n\r]/u.test(s)?`"${s.replaceAll('"','""')}"`:s};
const toCsv=rows=>rows.map(r=>r.map(csvCell).join(',')).join('\n');
const jsonRows=s=>{const x=JSON.parse(s);const a=Array.isArray(x)?x:[x];const keys=[...new Set(a.flatMap(v=>v&&typeof v==='object'&&!Array.isArray(v)?Object.keys(v):[]))];return keys.length?[keys,...a.map(v=>keys.map(k=>v?.[k]??''))]:a.map(v=>[v])};
const sqlRows=s=>{const q=text(s).trim();const m=q.match(/select\s+(.+?)\s+from\s+/is);if(!m)return [[q||'value']];const cols=m[1].trim()==='*'?['value']:m[1].split(',').map(x=>x.trim().replace(/^['"]|['"]$/g,''));return [cols,cols.map(c=>c.replace(/\s+as\s+.*/i,'').trim())]};
const yamlRows=s=>{const rows=[['key','value']];for(const line of text(s).split(/\r?\n/u)){const m=line.match(/^\s*([^:#][^:]*):\s*(.*)\s*$/);if(m)rows.push([m[1].trim(),m[2].trim()])}return rows.length>1?rows:csvParse(s)};
const rowsFrom=(s,n)=>{const v=text(s).trim();if(!v)return [['value'],['']];if(/json/i.test(n)){try{return jsonRows(v)}catch{}}if(/sql/i.test(n))return sqlRows(v);if(/yaml/i.test(n))return yamlRows(v);if(/tsv/i.test(n))return csvParse(v);if(/csv|excel|spreadsheet/i.test(n))return csvParse(v);if(/xml/i.test(n)){const pairs=[...v.matchAll(/<([A-Za-z_][\w:.-]*)>([^<]*)<\//g)].map(m=>[m[1],m[2]]);return pairs.length?[['key','value'],...pairs]:[['xml'],[v]]}return [[v]]};
const crc32=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0};
const u16=n=>new Uint8Array([n&255,(n>>>8)&255]);
const u32=n=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);
const cat=(a,b)=>{const x=new Uint8Array(a.length+b.length);x.set(a);x.set(b,a.length);return x};
function zipStore(files){const enc=new TextEncoder(),local=[],central=[];let offset=0;for(const [name,data] of files){const nb=enc.encode(name),db=typeof data==='string'?enc.encode(data):data,crc=crc32(db);const h=cat(cat(cat(cat(new Uint8Array([80,75,3,4,20,0,0,0,0,0]),u32(crc)),u32(db.length)),u32(db.length)),cat(u16(nb.length),u16(0)));local.push(cat(cat(h,nb),db));central.push({nb,crc,size:db.length,offset});offset+=local.at(-1).length}let body=new Uint8Array(0);for(const x of local)body=cat(body,x);let cd=new Uint8Array(0);for(const f of central){const h=cat(cat(cat(cat(new Uint8Array([80,75,1,2,20,0,20,0,0,0,0,0,0,0]),u32(f.crc)),u32(f.size)),u32(f.size)),cat(u16(f.nb.length),u16(0)));const fixed=cat(cat(cat(h,u16(0)),u16(0)),cat(cat(u32(0),u32(f.offset)),f.nb));cd=cat(cd,fixed)}const end=cat(cat(new Uint8Array([80,75,5,6,0,0,0,0]),u16(central.length)),cat(cat(u16(central.length),u32(cd.length)),cat(u32(body.length),u16(0))));return cat(cat(body,cd),end)}
const xlsxXml=rows=>{const sheet=rows.map((r,i)=>`<row r="${i+1}">${r.map((v,j)=>{const col=String.fromCharCode(65+(j%26))+Math.floor(j/26||0);return `<c r="${col}${i+1}" t="inlineStr"><is><t>${esc(v)}</t></is></c>`}).join('')}</row>`).join('');const files=[['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Sheet1" sheetId="1" r:id="rId1"/></sheets></workbook>'],['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],['xl/worksheets/sheet1.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheet}</sheetData></worksheet>`]];return new Blob([zipStore(files)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})};
const download=(blob,name)=>{if(!blob?.size)throw Error('The operation produced an empty file.');const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)};
function sqlFromRows(rows){const h=rows[0]||['value'];return `CREATE TABLE data (${h.map((x,i)=>`c${i+1} TEXT`).join(', ')});\nINSERT INTO data (${h.map((_,i)=>`c${i+1}`).join(', ')}) VALUES\n${rows.slice(1).map(r=>`(${r.map(v=>`'${text(v).replaceAll("'","''")}'`).join(', ')})`).join(',\n')};`}
export function mount(slug){const u=shell(document.querySelector('#toolApp'));const n=slug.replaceAll('-',' ').toLowerCase();const ta=document.createElement('textarea');ta.rows=14;ta.placeholder=/sql/i.test(n)?'Paste SQL or tabular data…':'Paste JSON, CSV, TSV, XML, YAML, SQL, or tabular data…';u.input.append(ta);u.actions.innerHTML='';const run=document.createElement('button');run.type='button';run.className='btn primary';run.textContent='Convert & download';u.actions.append(run);const status=(v,ok=true)=>{u.out.className=`zt-output output ${ok?'success':'error'}`;u.out.textContent=v};run.onclick=()=>{try{const rows=rowsFrom(ta.value,n);let blob,name;if(/to\s+(xlsx|excel|spreadsheet)|excel/i.test(n)&&!/from\s+excel/i.test(n)){blob=xlsxXml(rows);name='zero-trust.xlsx'}else if(/to\s+(csv)/i.test(n)){blob=new Blob([toCsv(rows)],{type:'text/csv;charset=utf-8'});name='zero-trust.csv'}else if(/to\s+(tsv)/i.test(n)){blob=new Blob([rows.map(r=>r.map(text).join('\t')).join('\n')],{type:'text/tab-separated-values;charset=utf-8'});name='zero-trust.tsv'}else if(/to\s+(xml)/i.test(n)){blob=new Blob([`<?xml version="1.0" encoding="UTF-8"?><rows>${rows.slice(1).map(r=>`<row>${r.map((v,i)=>`<c${i+1}>${esc(v)}</c${i+1}>`).join('')}</row>`).join('')}</rows>`],{type:'application/xml'});name='zero-trust.xml'}else if(/to\s+(yaml)/i.test(n)){blob=new Blob([rows.map(r=>`${r[0]??'value'}: ${r.slice(1).join(', ')}`).join('\n')],{type:'text/yaml'});name='zero-trust.yaml'}else if(/to\s+(sql)/i.test(n)){blob=new Blob([sqlFromRows(rows)],{type:'application/sql'});name='zero-trust.sql'}else{blob=new Blob([toCsv(rows)],{type:'text/csv;charset=utf-8'});name='zero-trust.csv'}download(blob,name);status(`Created ${name} from ${rows.length} row(s).`)}catch(e){status(e.message||'Data conversion failed.',false)}}}
