import {convert,resize,compressCanvas,loadImage,encode} from './image.js';
import {convert as unitConvert,categoryFromSlug} from './unit-engine.js';
import * as calc from './calculators.js';
import * as iv from './india-validators.js';
import * as data from './data-converters.js';
import * as text from './text-engine.js';
const base=location.pathname.startsWith('/Zero-trust/')?'/Zero-trust/':'/';
const slugify=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const formats=new Set(['jpg','jpeg','png','webp','bmp','ico']);
function fmtFromSlug(slug){const m=slug.match(/(?:^|-)to-(jpg|jpeg|png|webp|bmp|ico)(?:-converter)?$/i)||slug.match(/(jpg|jpeg|png|webp|bmp|ico)-converter$/i);return m?.[1]?.toLowerCase()}
function imageMount(slug){const target=fmtFromSlug(slug);const app=document.querySelector('#toolApp');if(!target)throw Error('Image conversion target could not be determined.');app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST · Canvas image engine</div><input id="ff" type="file" accept="image/*,.bmp,.ico,.svg"><div class="tool-actions"><button class="btn primary" id="fr">Convert to ${target.toUpperCase()}</button></div><div class="output" id="fo">Choose an image.</div></div>`;document.querySelector('#fr').onclick=async()=>{const o=document.querySelector('#fo');try{const f=document.querySelector('#ff').files[0];if(!f)throw Error('Choose an image.');const b=await convert(f,target);const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`converted.${target==='jpeg'?'jpg':target}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);o.textContent=`Converted ${Math.round(f.size/1024)}KB → ${Math.round(b.size/1024)}KB`;o.className='output success'}catch(e){o.textContent=e.message;o.className='output error'}}}
async function examMount(slug){const key=slugify(slug).replace(/-resizer$|-(photo|signature)-resizer$/,'');const r=await fetch(base+'config/india-exam-presets.json',{cache:'force-cache'});if(!r.ok)throw Error('Exam preset configuration unavailable.');const cfg=await r.json(),entry=cfg.presets[key]||Object.entries(cfg.presets).find(([k])=>slug.includes(k))?.[1];if(!entry)throw Error(`No verified preset profile is mapped for ${slug}.`);const app=document.querySelector('#toolApp');app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST · India exam preset</div><p>${entry.exam} ${entry.kind}: ${entry.widthPx}×${entry.heightPx}px · ${entry.dpi} DPI · ${entry.minKB}–${entry.maxKB}KB</p><input id="ef" type="file" accept="image/*,.bmp"><button class="btn primary" id="er">Apply preset & download</button><div class="output" id="eo">Choose an image.</div></div>`;document.querySelector('#er').onclick=async()=>{const o=document.querySelector('#eo');try{const f=document.querySelector('#ef').files[0];if(!f)throw Error('Choose an image.');const r=await resize(f,entry.widthPx,entry.heightPx,'jpg',.86);const c=await loadImage(f);const b=await resize(f,entry.widthPx,entry.heightPx,'jpg',.86);let out=b.blob;if(out.size>entry.maxKB*1024)out=await compressCanvas(await loadImage(f),'jpg',entry.maxKB*1024,{minQuality:.2,maxQuality:.86});if(out.size<entry.minKB*1024)throw Error(`Output is below the minimum ${entry.minKB}KB requirement. Use a higher-resolution/source image.`);const u=URL.createObjectURL(out),a=document.createElement('a');a.href=u;a.download=`${entry.exam}-${entry.kind}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);o.textContent=`${entry.widthPx}×${entry.heightPx}px · ${Math.round(out.size/1024)}KB`;o.className='output success'}catch(e){o.textContent=e.message;o.className='output error'}}}
function genericTextMount(kind,fn,label){const app=document.querySelector('#toolApp');app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST · ${label}</div><textarea id="fi" rows="12" placeholder="Input…"></textarea><button class="btn primary" id="go">Process</button><pre class="output" id="fo">Ready.</pre></div>`;document.querySelector('#go').onclick=()=>{try{const r=fn(document.querySelector('#fi').value);document.querySelector('#fo').textContent=typeof r==='string'?r:JSON.stringify(r,null,2);document.querySelector('#fo').className='output success'}catch(e){document.querySelector('#fo').textContent=e.message;document.querySelector('#fo').className='output error'}}}
function dataMount(slug){const s=slug.toLowerCase();if(/json.*csv|csv.*json/.test(s))return genericTextMount('data',s.startsWith('json')?x=>data.jsonToCSV(JSON.parse(x)):data.csvToJSON,'JSON/CSV');if(/json.*xml|xml.*json/.test(s))return genericTextMount('data',s.startsWith('json')?x=>data.jsonToXML(JSON.parse(x)):data.xmlToJSON,'JSON/XML');if(/yaml.*json|json.*yaml/.test(s))return genericTextMount('data',s.startsWith('yaml')?data.yamlToJSON:x=>{throw Error('JSON→YAML is not implemented by the lightweight YAML writer yet.')},'JSON/YAML');const map=[[/base64/,data.encodeBase64,'Base64'],[/hex/,data.encodeHex,'Hex'],[/binary/,data.encodeBinary,'Binary'],[/url.*(encode|decode)/,data.urlEncode,'URL'],[/html.*entity/,data.htmlEncode,'HTML entities']];const m=map.find(([re])=>re.test(s));if(m)return genericTextMount('data',m[1],m[2]);throw Error(`No data conversion mapping for ${slug}.`)}
function textMount(slug){const s=slug.toLowerCase();if(/diff|levenshtein/.test(s)){const app=document.querySelector('#toolApp');app.innerHTML='<div class="zt-card"><textarea id="a" rows="6"></textarea><textarea id="b" rows="6"></textarea><button class="btn primary" id="d">Compare</button><pre class="output" id="o">Ready.</pre></div>';document.querySelector('#d').onclick=()=>{const r=/levenshtein/.test(s)?text.levenshtein(document.querySelector('#a').value,document.querySelector('#b').value):text.diff(document.querySelector('#a').value,document.querySelector('#b').value);document.querySelector('#o').textContent=JSON.stringify(r,null,2)};return}const op=Object.keys({camel:1,pascal:1,snake:1,kebab:1,title:1,sentence:1,counts:1,sortLines:1,uniqueLines:1,stripWhitespace:1,stripNewlines:1}).find(k=>s.includes(k.replace('strip','strip-'))||s.includes(k));if(op)return genericTextMount('text',text[op],op);throw Error(`No text operation mapped for ${slug}.`)}
function calcMount(slug){return calc.mount(slug)}
function validatorMount(slug){return iv.mount(slug)}
export async function mount(slug,meta={}){const s=slug.toLowerCase();if(fmtFromSlug(s)&&formats.has(fmtFromSlug(s)))return imageMount(s);if(/(upsc|ssc|ibps|neet|jee|gate|psc).*(photo|signature).*(resize|size|compress)|exam.*(photo|signature)/.test(s))return examMount(s);if(/(^|-)to-.*(-|$)|unit|converter/.test(s)&&/(length|mass|weight|area|volume|speed|data|storage|time|meter|inch|foot|mile|kg|gram|liter|gallon|byte)/.test(s))return genericTextMount('unit',()=>unitConvert(document.querySelector('#uv').value,categoryFromSlug(s),document.querySelector('#uf').value,document.querySelector('#ut').value),'Unit');if(/sip|emi|ppf|cagr|nps|bmi|bmr|gst|compound-interest|calorie-deficit/.test(s))return calcMount(s);if(/pan|aadhaar|aadhar|gstin|ifsc/.test(s))return validatorMount(s);if(/json.*(csv|xml|yaml)|csv.*json|xml.*json|yaml.*json|base64|hex|binary|url.*(encode|decode)|html.*entity/.test(s))return dataMount(s);if(/camel|pascal|snake|kebab|title-case|sentence-case|word-count|character-count|reading-time|sort-lines|duplicate|whitespace|newline|levenshtein|text-diff/.test(s))return textMount(s);return null}
