const MAX_BYTES=30*1024*1024,MAX_PIXELS=16_000_000;
const mime={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp'};
const ext=name=>String(name).toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'';
export const boundedCanvas=(w,h)=>{const scale=Math.min(1,Math.sqrt(MAX_PIXELS/(Math.max(1,w)*Math.max(1,h))));const c=document.createElement('canvas');c.width=Math.max(1,Math.floor(w*scale));c.height=Math.max(1,Math.floor(h*scale));return c};
function bmpCanvas(buf){const d=new DataView(buf);if(d.getUint16(0,true)!==0x4d42)throw Error('Invalid BMP.');const off=d.getUint32(10,true),dib=d.getUint32(14,true),w=d.getInt32(18,true),hh=d.getInt32(22,true),planes=d.getUint16(26,true),bits=d.getUint16(28,true),compression=d.getUint32(30,true);if(dib<40||planes!==1||!([24,32].includes(bits))||compression!==0)throw Error('BMP decoder supports uncompressed 24/32-bit BMP only.');const h=Math.abs(hh),top=hh<0,c=boundedCanvas(w,h),ctx=c.getContext('2d'),img=ctx.createImageData(c.width,c.height),srcStride=Math.floor((w*bits/8+3)/4)*4;for(let y=0;y<h;y++){const sy=top?y:h-1-y;for(let x=0;x<w;x++){const p=off+sy*srcStride+x*(bits/8),q=(y*c.width+x)*4;img.data[q]=d.getUint8(p+2);img.data[q+1]=d.getUint8(p+1);img.data[q+2]=d.getUint8(p);img.data[q+3]=bits===32?d.getUint8(p+3):255}}ctx.putImageData(img,0,0);return c}
export async function loadImage(file){if(file.size>MAX_BYTES)throw Error('Image exceeds the 30MB browser limit.');const e=ext(file.name);if(['raw','cr2','nef','arw','dng'].includes(e))throw Error('Direct client-side conversion to RAW is not technically feasible in-browser.');if(e==='bmp'){return bmpCanvas(await file.arrayBuffer())}if(['tif','tiff','heic','heif'].includes(e))throw Error(`${e.toUpperCase()} decoding is not guaranteed by the browser-safe engine. Use PNG/JPG/WebP/BMP input.`);if(e==='ico')throw Error('ICO input is not guaranteed by the browser-safe engine. Exporting to ICO is not supported; use PNG/JPG input.');const u=URL.createObjectURL(file),im=new Image();try{im.src=u;await im.decode();const c=boundedCanvas(im.naturalWidth,im.naturalHeight);c.getContext('2d',{alpha:true}).drawImage(im,0,0,c.width,c.height);return c}finally{URL.revokeObjectURL(u)}}
export const encode=async(c,target='png',quality=.9)=>{if(!mime[target])throw Error(`Browser-safe ${target.toUpperCase()} encoding is unavailable.`);const b=await new Promise(r=>c.toBlob(r,mime[target],quality));if(!b)throw Error(`The browser could not encode ${target.toUpperCase()}.`);return b};
export async function compress(file,target='jpg',targetBytes=0){const c=await loadImage(file);if(!targetBytes)return encode(c,target,.82);return compressCanvas(c,target,targetBytes)}
export async function compressCanvas(c,target,targetBytes,{minQuality=.2,maxQuality=.98,tolerance=.015,maxIterations=12}={}){if(targetBytes<1)throw Error('Target size must be positive.');let lo=minQuality,hi=maxQuality,best=null;for(let i=0;i<maxIterations;i++){const q=(lo+hi)/2,b=await encode(c,target,q);if(!best||Math.abs(b.size-targetBytes)<Math.abs(best.size-targetBytes))best=b;if(b.size>targetBytes)hi=q;else lo=q;if(Math.abs(b.size-targetBytes)<=Math.max(1,targetBytes*tolerance))return b}if(best&&best.size<=targetBytes)return best;throw Error(`Could not reach the requested target size without unacceptable quality loss. Closest result: ${Math.round((best?.size||0)/1024)}KB.`)}
export async function resize(file,w,h,target='png',quality=.9){const src=await loadImage(file),rw=Math.max(1,Math.round(w||src.width)),rh=Math.max(1,Math.round(h||src.height));if(rw*rh>MAX_PIXELS)throw Error('Requested dimensions exceed the 16 megapixel browser limit.');const c=document.createElement('canvas');c.width=rw;c.height=rh;c.getContext('2d').drawImage(src,0,0,rw,rh);return{blob:await encode(c,target,quality),width:rw,height:rh}}
export async function convert(file,target){const c=await loadImage(file);return encode(c,target,.9)}
