/* Extended image format codec. Native decoding is preferred; WASM decoders are lazy. */
const $=(s,p=document)=>p.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const out=(o,v,ok=true)=>{o.className=`zt-output output ${ok?'success':'error'}`;o.innerHTML=`<pre>${esc(v)}</pre>`};
const btn=(t,f)=>{const b=document.createElement('button');b.type='button';b.className='btn primary';b.textContent=t;b.onclick=f;return b};
const dl=(b,n)=>{if(!b?.size)throw Error('The image codec produced an empty artifact.');const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)};
const ext=s=>s.toLowerCase().split('.').pop();
const targetFrom=n=>(n.match(/\bto\s+(jpg|jpeg|png|webp|avif|gif|bmp|tiff|svg|ico|pdf)\b/i)||[])[1]?.toLowerCase()||'png';
const mime=t=>t==='jpg'||t==='jpeg'?'image/jpeg':t==='webp'?'image/webp':t==='avif'?'image/avif':t==='gif'?'image/gif':t==='bmp'?'image/bmp':t==='tiff'?'image/tiff':t==='svg'?'image/svg+xml':'image/png';
async function native(file){const u=URL.createObjectURL(file),im=new Image();im.src=u;await im.decode();const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);URL.revokeObjectURL(u);return c}
async function tiff(file){const M=await import('https://cdn.jsdelivr.net/npm/utif@3.1.0/+esm'),U=M.default||M,bytes=await file.arrayBuffer(),ifs=U.decode(bytes);if(!ifs.length)throw Error('No TIFF image directory found.');U.decodeImage(bytes,ifs[0]);const rgba=U.toRGBA8(ifs[0]),c=document.createElement('canvas');c.width=ifs[0].width;c.height=ifs[0].height;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(rgba),c.width,c.height),0,0);return c}
async function heic(file){const M=await import('https://cdn.jsdelivr.net/npm/heic-decode@2.1.0/+esm'),decode=M.default||M,im=await decode({buffer:new Uint8Array(await file.arrayBuffer())}),c=document.createElement('canvas');c.width=im.width;c.height=im.height;c.getContext('2d').putImageData(new ImageData(im.data,im.width,im.height),0,0);return c}
async function raw(file){const M=await import('https://cdn.jsdelivr.net/npm/libraw-wasm@1.6.0/+esm'),LibRaw=M.default||M.LibRaw||M,decoder=new LibRaw();await decoder.open(new Uint8Array(await file.arrayBuffer()),{halfSize:true,useCameraWb:true});const im=await decoder.imageData();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const rgba=new Uint8ClampedArray(im.width*im.height*4),src=im.data,channels=im.colors||3;for(let i=0,j=0;i<im.width*im.height;i++,j+=channels){rgba[i*4]=src[j];rgba[i*4+1]=src[j+1]??src[j];rgba[i*4+2]=src[j+2]??src[j];rgba[i*4+3]=255}c.getContext('2d').putImageData(new ImageData(rgba,c.width,c.height),0,0);return c}
async function pdfCanvas(file){const P=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs'),pdf=await P.getDocument({data:await file.arrayBuffer()}).promise,arr=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;arr.push(c)}return arr}
async function canvasPdf(canvas){const P=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm'),pdf=P.PDFDocument.create(),page=pdf.addPage([canvas.width*72/96,canvas.height*72/96]);const jpg=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.92)),bytes=new Uint8Array(await jpg.arrayBuffer()),img=await pdf.embedJpg(bytes);page.drawImage(img,{x:0,y:0,width:page.getWidth(),height:page.getHeight()});return new Blob([await pdf.save()],{type:'application/pdf'})}
async function encode(canvas,t){if(t==='pdf')return canvasPdf(canvas);if(t==='svg'){const d=canvas.toDataURL('image/png');return new Blob([`<svg xmlns="http://www.w3.org/2000/svg" width="${canvas.width}" height="${canvas.height}" viewBox="0 0 ${canvas.width} ${canvas.height}"><image href="${d}" width="100%" height="100%"/></svg>`],{type:'image/svg+xml'})}if(t==='tiff'){const U=(await import('https://cdn.jsdelivr.net/npm/utif@3.1.0/+esm'));const u=U.default||U,rgba=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;return new Blob([u.encodeImage(rgba,canvas.width,canvas.height)],{type:'image/tiff'})}const b=await new Promise(r=>canvas.toBlob(r,mime(t),t==='jpg'||t==='jpeg'?.92:0.9));if(!b)throw Error(`Browser cannot encode ${t.toUpperCase()} on this device.`);return b}
export async function mount(slug){const app=$('#toolApp');if(!app)return;let tools=window.ZT_TOOLS;const base=location.pathname.startsWith('/Zero-trust/')?'/Zero-trust/':'/';if(!tools)tools=await fetch(base+'data/tools-index.json',{cache:'force-cache'}).then(r=>r.json());const meta=(tools||[]).find(x=>x.slug===slug)||{name:slug.replace(/-/g,' ')};const n=meta.name.toLowerCase(),target=targetFrom(n);app.innerHTML='<div class="zt-card"><div class="zt-local">LOCAL-FIRST FORMAT CODEC — RAW/TIFF/HEIC/PDF decoders load only when required</div><div class="zt-input"></div><div class="zt-actions tool-actions"></div><div class="zt-output output">Choose an image.</div></div>';const input=document.createElement('input');input.type='file';input.accept='image/*,.cr2,.nef,.arw,.dng,.tif,.tiff,.heic,.heif,.pdf';app.querySelector('.zt-input').append(input);app.querySelector('.zt-actions').append(btn('Convert',async()=>{try{const file=input.files[0];if(!file)throw Error('Choose an input image/file first.');if(file.size>75*1024*1024)throw Error('File exceeds the 75MB browser safety limit.');const e=ext(file),can=e==='pdf'?await pdfCanvas(file):e==='tif'||e==='tiff'?await tiff(file):e==='heic'||e==='heif'?await heic(file):/^(cr2|nef|arw|dng|raf|rw2|orf|srw)$/u.test(e)?await raw(file):[await native(file)];if(target==='pdf'&&can.length===1){const b=await canvasPdf(can[0]);dl(b,`${slug}.pdf`);out(app.querySelector('.zt-output'),`Converted ${file.name} → PDF · ${b.size.toLocaleString()} bytes`);return}if(target==='pdf'){const P=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm'),pdf=await P.PDFDocument.create();for(const c of can){const jpg=await new Promise(r=>c.toBlob(r,'image/jpeg',.92)),img=await pdf.embedJpg(new Uint8Array(await jpg.arrayBuffer())),p=pdf.addPage([c.width*72/96,c.height*72/96]);p.drawImage(img,{x:0,y:0,width:p.getWidth(),height:p.getHeight()})}const b=new Blob([await pdf.save()],{type:'application/pdf'});dl(b,`${slug}.pdf`);out(app.querySelector('.zt-output'),`Converted ${can.length} page(s) → PDF · ${b.size.toLocaleString()} bytes`);return}if(can.length===1){const b=await encode(can[0],target);dl(b,`${slug}.${target==='jpg'?'jpg':target}`);out(app.querySelector('.zt-output'),`Converted ${file.name} → ${target.toUpperCase()} · ${b.size.toLocaleString()} bytes`)}else{const Z=(await import('https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm'));const z=new (Z.default||Z)();for(let i=0;i<can.length;i++)z.file(`page-${String(i+1).padStart(3,'0')}.${target}`,await encode(can[i],target));const b=await z.generateAsync({type:'blob',compression:'DEFLATE'});dl(b,`${slug}-pages.zip`);out(app.querySelector('.zt-output'),`Converted ${can.length} pages. Downloaded as ZIP · ${b.size.toLocaleString()} bytes`)}}catch(e){out(app.querySelector('.zt-output'),e.message||'Image conversion failed.',false)}}));}
