const MAX=75*1024*1024;
const $=(s,p=document)=>p.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const out=(o,v,ok=true)=>{o.className=`zt-output output ${ok?'success':'error'}`;o.innerHTML=`<pre>${esc(v)}</pre>`};
const btn=(t,f,p=false)=>{const b=document.createElement('button');b.type='button';b.className=`btn${p?' primary':''}`;b.textContent=t;b.onclick=f;return b};
const pick=p=>{const l=document.createElement('label');l.className='upload-zone';l.innerHTML='<strong>Choose media file</strong><span>Maximum 75MB for safe in-browser conversion</span>';const i=document.createElement('input');i.type='file';i.accept='audio/*,video/*';l.append(i);p.append(l);return i};
const shell=app=>{app.innerHTML='<div class="zt-card"><div class="zt-local">LOCAL-FIRST MEDIA PROCESSING — conversion runs in a dedicated Web Worker</div><div class="zt-input"></div><div class="zt-options control-grid"></div><div class="zt-actions tool-actions"></div><div class="zt-output output" aria-live="polite">Ready.</div></div>';return{input:$('.zt-input',app),options:$('.zt-options',app),actions:$('.zt-actions',app),out:$('.zt-output',app)}};
const download=(b,n)=>{if(!b?.size)throw Error('The conversion produced an empty artifact.');const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)};
const mime=f=>/mp3/u.test(f)?'audio/mpeg':/wav/u.test(f)?'audio/wav':/flac/u.test(f)?'audio/flac':/ogg/u.test(f)?'audio/ogg':/webm/u.test(f)?'video/webm':/gif/u.test(f)?'image/gif':'video/mp4';
export async function mount(slug){const app=$('#toolApp');if(!app)return;const u=shell(app),n=slug.replace(/-/g,' ').toLowerCase(),f=pick(u.input);const format=(n.match(/\bto\s+(mp3|wav|aac|ogg|flac|m4a|wma|opus|aiff|mp4|mov|avi|mkv|webm|flv|wmv|3gp|mpeg|gif)\b/)||[])[1]||(/extract audio/u.test(n)?'mp3':/video to gif|gif/u.test(n)?'gif':'mp4');const w=new Worker(new URL('./media-worker.js',import.meta.url),{type:'module'});let id=0;const convert=(file,args,outputName)=>new Promise((resolve,reject)=>{const request=++id;const timer=setTimeout(()=>{w.terminate();reject(new Error('Media conversion exceeded the safety timeout.'))},180000);w.onmessage=e=>{if(e.data.id!==request)return;clearTimeout(timer);e.data.ok?resolve(new Blob([e.data.result],{type:mime(format)})):reject(new Error(e.data.error))};w.onerror=()=>{clearTimeout(timer);reject(new Error('Media worker failed.'))};file.arrayBuffer().then(input=>w.postMessage({id:request,inputName:'input.'+(file.name.split('.').pop()||'bin'),input,outputName,args},[input])).catch(reject)});u.actions.append(btn('Convert',async()=>{try{const file=f.files[0];if(!file)throw Error('Choose an audio or video file first.');if(file.size>MAX)throw Error('File exceeds the 75MB browser safety limit. Use a desktop/local application for larger media.');const inputName='input.'+(file.name.split('.').pop()||'bin'),outputName=`zero-trust-output.${format}`;const args=['-i',inputName];if(/extract audio/u.test(n))args.push('-vn','-c:a',format==='wav'?'pcm_s16le':format==='flac'?'flac':'libmp3lame','-y',outputName);else if(format==='gif')args.push('-vf','fps=12,scale=640:-1:flags=lanczos','-y',outputName);else if(['mp4','mkv','webm','mov','avi'].includes(format))args.push('-c:v',format==='webm'?'libvpx-vp9':'libx264','-c:a',format==='webm'?'libopus':'aac','-y',outputName);else if(['mp3','aac','ogg','flac','wav','opus'].includes(format))args.push('-vn','-c:a',format==='mp3'?'libmp3lame':format,'-y',outputName);else throw Error(`Codec target ${format.toUpperCase()} is not supported by the browser build.`);const blob=await convert(file,args,outputName);download(blob,outputName);out(u.out,`Converted ${file.name} → ${outputName}\nOutput size: ${blob.size.toLocaleString()} bytes`)}catch(e){out(u.out,e.message||'Media conversion failed.',false)}} ,true));}
