/* Lazy media codec. FFmpeg is downloaded only when an audio/video tool is actually used. */
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=(s,p=document)=>p.querySelector(s);
const out=(o,v,ok=true)=>{o.className=`zt-output output ${ok?'success':'error'}`;o.innerHTML=`<pre>${esc(v)}</pre>`};
const btn=(t,f,p=false)=>{const b=document.createElement('button');b.type='button';b.className=`btn${p?' primary':''}`;b.textContent=t;b.onclick=f;return b};
const pick=p=>{const l=document.createElement('label');l.className='upload-zone';l.innerHTML='<strong>Choose media file</strong><span>Audio/video codecs load only when processing starts</span>';const i=document.createElement('input');i.type='file';i.accept='audio/*,video/*';l.append(i);p.append(l);return i};
const shell=app=>{app.innerHTML='<div class="zt-card"><div class="zt-local">LOCAL-FIRST MEDIA PROCESSING — codec loads on demand</div><div class="zt-input"></div><div class="zt-options control-grid"></div><div class="zt-actions tool-actions"></div><div class="zt-output output" aria-live="polite">Ready.</div></div>';return{input:$('.zt-input',app),options:$('.zt-options',app),actions:$('.zt-actions',app),out:$('.zt-output',app)}};
const download=(b,n)=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)};
let codecPromise;
async function codec(){if(codecPromise)return codecPromise;codecPromise=(async()=>{const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import('https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@0.12.10/+esm'),import('https://cdn.jsdelivr.net/npm/@ffmpeg/util@0.12.1/+esm')]);const f=new FFmpeg();const root='https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd';await f.load({coreURL:await toBlobURL(`${root}/ffmpeg-core.js`,'text/javascript'),wasmURL:await toBlobURL(`${root}/ffmpeg-core.wasm`,'application/wasm')});return{f,fetchFile}})();return codecPromise}
export async function mount(slug){const app=$('#toolApp');if(!app)return;const u=shell(app),n=slug.replace(/-/g,' ').toLowerCase(),f=pick(u.input);const format=(n.match(/\bto\s+(mp3|wav|aac|ogg|flac|m4a|wma|opus|aiff|mp4|mov|avi|mkv|webm|flv|wmv|3gp|mpeg|gif)\b/)||[])[1]||(/extract audio/u.test(n)?'mp3':/video to gif|gif/u.test(n)?'gif':'mp4');u.actions.append(btn('Convert',async()=>{try{const file=f.files[0];if(!file)throw Error('Choose an audio or video file first.');const {f:ff,fetchFile}=await codec();const inputName='input.'+(file.name.split('.').pop()||'bin');const ext=format==='mp4'?'mp4':format;const outputName=`zero-trust-output.${ext}`;await ff.writeFile(inputName,await fetchFile(file));const args=['-i',inputName];if(/extract audio/u.test(n)){args.push('-vn','-c:a',format==='wav'?'pcm_s16le':format==='flac'?'flac':'libmp3lame','-y',outputName)}else if(format==='gif'){args.push('-vf','fps=12,scale=640:-1:flags=lanczos','-y',outputName)}else if(['mp4','mkv','webm','mov','avi'].includes(format)){args.push('-c:v',format==='webm'?'libvpx-vp9':'libx264','-c:a',format==='webm'?'libopus':'aac','-y',outputName)}else if(['mp3','aac','ogg','flac','wav','opus'].includes(format)){args.push('-vn','-c:a',format==='mp3'?'libmp3lame':format,'-y',outputName)}else throw Error(`Codec target ${format.toUpperCase()} is not supported by the browser build.`);const code=await ff.exec(args);if(code!==0)throw Error(`FFmpeg could not encode this file as ${format.toUpperCase()}.`);const data=await ff.readFile(outputName);const mime=/mp3/u.test(format)?'audio/mpeg':/wav/u.test(format)?'audio/wav':/flac/u.test(format)?'audio/flac':/ogg/u.test(format)?'audio/ogg':/webm/u.test(format)?'video/webm':/gif/u.test(format)?'image/gif':'video/mp4';const blob=new Blob([data],{type:mime});download(blob,outputName);out(u.out,`Converted ${file.name} → ${outputName}\nOutput size: ${blob.size.toLocaleString()} bytes`);await ff.deleteFile(inputName).catch(()=>{});await ff.deleteFile(outputName).catch(()=>{})}catch(e){out(u.out,e.message||'Media conversion failed.',false)}},true))}
