const PDF=()=>import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');
const PDFJS=()=>import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/+esm').then(m=>{m.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs';return m});
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const download=(b,n)=>{if(!b||!b.size)throw Error('The operation produced an empty PDF artifact.');const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)};
const load=async f=>(await PDF()).PDFDocument.load(await f.arrayBuffer());
const picker=(p,m=false)=>{const i=document.createElement('input');i.type='file';i.accept='application/pdf';i.multiple=m;p.append(i);return i};
const out=(o,x,ok=true)=>{o.className=`output ${ok?'success':'error'}`;o.innerHTML=`<pre>${esc(x)}</pre>`};
export async function mount(slug){const base=location.pathname.startsWith('/Zero-trust/')?'/Zero-trust/':'/';let tools=window.ZT_TOOLS;if(!tools)tools=await fetch(base+'data/tools-index.json').then(r=>r.json());window.ZT_TOOLS=tools;const meta=tools.find(x=>x.slug===slug)||{name:slug.replace(/-/g,' ')};const n=meta.name.toLowerCase();const app=$('#toolApp');app.innerHTML='<div class="zt-card"><div class="zt-local">REAL PDF PROCESSING — browser PDF library loaded from CDN</div><div id="pdfInput"></div><div id="pdfOptions"></div><div class="tool-actions"><button class="btn primary" id="pdfRun">Run</button></div><div id="pdfOut" class="output">Ready.</div></div>';const input=$('#pdfInput'),opts=$('#pdfOptions'),o=$('#pdfOut');const multi=/merge pdf|combine images/i.test(n);const f=picker(input,multi);if(/rotate/i.test(n))opts.innerHTML='<label>Degrees<input id="degrees" type="number" value="90"></label>';if(/crop/i.test(n))opts.innerHTML='<label>Crop points <input id="crop" value="10,10,10,10"></label>';if(/page numbers|header\/footer/i.test(n))opts.innerHTML='<label>Text<input id="text" value="Page "></label>';if(/extract|delete|reorder|split/i.test(n))opts.innerHTML='<label>Pages<input id="pages" placeholder="1,3-5"></label>';if(n.includes('edit pdf metadata'))opts.innerHTML='<label>Title<input id="value" maxlength="500" placeholder="New PDF title"></label>';$('#pdfRun').onclick=async()=>{try{const A=await PDF();if(n.includes('combine images')){if(!f.files.length)throw Error('Choose images.');const d=await A.PDFDocument.create();for(const file of f.files){if(!file.type.startsWith('image/'))continue;let im;if(file.type==='image/png')im=await d.embedPng(await file.arrayBuffer());else{const img=new Image(),u=URL.createObjectURL(file);img.src=u;await img.decode();const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);const b=await new Promise(r=>c.toBlob(r,'image/jpeg',.92));im=await d.embedJpg(await b.arrayBuffer());URL.revokeObjectURL(u)}const p=d.addPage([im.width,im.height]);p.drawImage(im,{x:0,y:0,width:im.width,height:im.height})}const b=new Blob([await d.save()],{type:'application/pdf'});download(b,'images-to-pdf.pdf');return out(o,'Created image PDF artifact.')}
if(!f.files.length)throw Error('Choose a PDF first.');const src=await load(f.files[0]),count=src.getPageCount();if(n==='pdf page counter')return out(o,`${count} page(s).`);if(n.includes('merge pdf')){if(f.files.length<2)throw Error('Choose at least two PDFs.');const d=await A.PDFDocument.create();for(const file of f.files){const x=await load(file);(await d.copyPages(x,x.getPageIndices())).forEach(p=>d.addPage(p))}const b=new Blob([await d.save()],{type:'application/pdf'});download(b,'merged.pdf');return out(o,`Merged ${d.getPageCount()} pages.`)}
if(n.includes('split pdf')||n.includes('extract pdf pages')||n.includes('delete pdf pages')||n.includes('reorder pdf pages')){const raw=($('#pages')?.value||'').split(',').flatMap(v=>{const m=v.trim().match(/^(\d+)(?:-(\d+))?$/);if(!m)return[];const a=+m[1],b=+(m[2]||m[1]);return Array.from({length:Math.max(0,b-a+1)},(_,i)=>a+i)}).filter(x=>x>=1&&x<=count);const wanted=raw.length?[...new Set(raw)]:src.getPageIndices().map(x=>x+1);let ids=wanted.map(x=>x-1);if(n.includes('delete pdf pages')){const del=new Set(ids);ids=src.getPageIndices().filter(x=>!del.has(x))}const d=await A.PDFDocument.create();(await d.copyPages(src,ids)).forEach(p=>d.addPage(p));const b=new Blob([await d.save()],{type:'application/pdf'});download(b,`${slug}.pdf`);return out(o,`Created ${d.getPageCount()} page PDF.`)}
if(n.includes('rotate pdf')||n.includes('crop pdf')||n.includes('scale/resize pdf pages')){for(const p of src.getPages()){if(n.includes('rotate'))p.setRotation(A.degrees(p.getRotation().angle+(Number($('#degrees')?.value)||90)));if(n.includes('crop')){const q=($('#crop')?.value||'10,10,10,10').split(',').map(Number);const[l,b,r,t]=q;p.setCropBox(l,b,Math.max(1,p.getWidth()-l-r),Math.max(1,p.getHeight()-b-t))}if(n.includes('scale/resize'))p.scale(1.1,1.1)}const b=new Blob([await src.save()],{type:'application/pdf'});download(b,`${slug}.pdf`);return out(o,'PDF artifact created.')}
if(n.includes('edit pdf metadata')){const v=$('#value')?.value||'';src.setTitle(v);const b=new Blob([await src.save()],{type:'application/pdf'});download(b,`${slug}.pdf`);return out(o,'Metadata updated.')}
if(n.includes('metadata'))return out(o,JSON.stringify({title:src.getTitle()||'',author:src.getAuthor()||'',subject:src.getSubject()||'',keywords:src.getKeywords()||'',creator:src.getCreator()||'',producer:src.getProducer()||'',pages:count},null,2));
if(n.includes('add page numbers')||n.includes('header/footer')||n.includes('watermark')){const font=await src.embedFont(A.StandardFonts.Helvetica),text=$('#text')?.value||'Page ';src.getPages().forEach((p,i)=>p.drawText(n.includes('watermark')?'Zero Trust':`${text}${i+1}`,{x:30,y:n.includes('header')?p.getHeight()-30:30,size:14,font,opacity:.7}));const b=new Blob([await src.save()],{type:'application/pdf'});download(b,`${slug}.pdf`);return out(o,'PDF artifact created.')}
if(n.includes('pdf to single images')){const M=await PDFJS(),doc=await M.getDocument({data:new Uint8Array(await f.files[0].arrayBuffer())}).promise;for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const b=await new Promise(r=>c.toBlob(r,'image/png'));download(b,`page-${i}.png`)}return out(o,`Rendered ${doc.numPages} page(s).`)}
throw Error(`No exact PDF operation is implemented for “${meta.name}”.`);
}catch(e){out(o,e.message,false)}}}
