const MAX=30*1024*1024;
const MAX_PIXELS=16_000_000;
const $=s=>document.querySelector(s);
const out=(o,v,ok=true)=>{o.className=`zt-output output ${ok?'success':'error'}`;o.textContent=v};
const dl=(b,n)=>{if(!b?.size)throw Error('Image operation produced an empty artifact.');const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clampCanvas=(w,h)=>{const scale=Math.min(1,Math.sqrt(MAX_PIXELS/(Math.max(1,w)*Math.max(1,h))));const c=document.createElement('canvas');c.width=Math.max(1,Math.floor(w*scale));c.height=Math.max(1,Math.floor(h*scale));return c};
const extOf=name=>{const m=String(name).toLowerCase().match(/\.([a-z0-9]+)$/);return m?.[1]||''};
const MIME={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',avif:'image/avif',gif:'image/gif',bmp:'image/bmp'};
const NATIVE_INPUT=new Set(['jpg','jpeg','png','webp','avif','gif','bmp']);
const NATIVE_OUTPUT=new Set(['jpg','jpeg','png','webp','avif','gif','bmp']);
async function loadNative(file){const u=URL.createObjectURL(file),im=new Image();try{im.src=u;await im.decode();const c=clampCanvas(im.naturalWidth,im.naturalHeight);c.getContext('2d',{alpha:true}).drawImage(im,0,0,c.width,c.height);return c}finally{URL.revokeObjectURL(u)}}
async function loadSvg(file){const text=await file.text();if(!/<svg[\s>]/i.test(text))throw Error('Invalid SVG input.');const blob=new Blob([text],{type:'image/svg+xml'}),u=URL.createObjectURL(blob),im=new Image();try{im.src=u;await im.decode();const c=clampCanvas(im.naturalWidth||1024,im.naturalHeight||1024);c.getContext('2d').drawImage(im,0,0,c.width,c.height);return c}finally{URL.revokeObjectURL(u)}}
async function loadHeic(file){const mod=await import('https://cdn.jsdelivr.net/npm/heic2any@0.0.4/+esm');const result=await mod.default({blob:file,toType:'image/png',quality:1});const blob=Array.isArray(result)?result[0]:result;return loadNative(new File([blob],'decoded.png',{type:'image/png'}))}
async function loadImage(file){const ext=extOf(file.name);if(ext==='svg')return loadSvg(file);if(ext==='heic'||ext==='heif'||file.type==='image/heic'||file.type==='image/heif')return loadHeic(file);if(ext==='tif'||ext==='tiff'){const mod=await import('https://cdn.jsdelivr.net/npm/utif@3.1.0/+esm');const bytes=new Uint8Array(await file.arrayBuffer()),ifds=mod.decode(bytes);if(!ifds.length)throw Error('No TIFF image found.');mod.decodeImage(bytes,ifds[0]);const rgba=mod.toRGBA8(ifds[0]),w=ifds[0].width,h=ifds[0].height,c=clampCanvas(w,h),img=new ImageData(new Uint8ClampedArray(rgba),w,h);c.getContext('2d').putImageData(img,0,0);return c}if(ext==='raw')throw Error('RAW camera input is not safely decodable by this browser engine yet. No file is uploaded.');if(ext==='ico')throw Error('ICO input decoding is not guaranteed across browsers; use PNG/JPG as the source.');if(!NATIVE_INPUT.has(ext))throw Error(`Unsupported input format: ${ext.toUpperCase()||'unknown'}.`);return loadNative(file)}
function rgbaFromCanvas(c){return c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height)}
function encodeTiff(c){const {data,width:w,height:h}=rgbaFromCanvas(c),entries=10,ifdOffset=8,ifdSize=2+entries*12+4,bitsOffset=ifdOffset+ifdSize,pixelOffset=bitsOffset+8,total=pixelOffset+w*h*4,b=new ArrayBuffer(total),v=new DataView(b),u=new Uint8Array(b);v.setUint16(0,0x4949,true);v.setUint16(2,42,true);v.setUint32(4,ifdOffset,true);v.setUint16(ifdOffset,entries,true);let p=ifdOffset+2;const tag=(id,type,count,val)=>{v.setUint16(p,id,true);v.setUint16(p+2,type,true);v.setUint32(p+4,count,true);if(type===3&&count===1)v.setUint16(p+8,val,true);else v.setUint32(p+8,val,true);p+=12};tag(256,3,1,w);tag(257,3,1,h);tag(258,3,4,bitsOffset);tag(259,3,1,1);tag(262,3,1,2);tag(273,4,1,pixelOffset);tag(277,3,1,4);tag(278,4,1,h);tag(279,4,1,w*h*4);tag(338,3,1,1);v.setUint32(p,0,true);for(let i=0;i<4;i++)v.setUint16(bitsOffset+i*2,8,true);let q=pixelOffset;for(let i=0;i<data.length;i+=4){u[q++]=data[i];u[q++]=data[i+1];u[q++]=data[i+2];u[q++]=data[i+3]}return new Blob([b],{type:'image/tiff'})}
async function makeIco(c){const size=Math.min(256,Math.max(16,Math.min(c.width,c.height))),tmp=document.createElement('canvas');tmp.width=size;tmp.height=size;tmp.getContext('2d').drawImage(c,0,0,size,size);const png=await new Promise(r=>tmp.toBlob(r,'image/png'));if(!png)throw Error('ICO payload encoding failed.');const bytes=new Uint8Array(await png.arrayBuffer()),b=new ArrayBuffer(22+bytes.length),v=new DataView(b),u=new Uint8Array(b);v.setUint16(2,1,true);v.setUint16(4,1,true);u[6]=size===256?0:size;u[7]=size===256?0:size;v.setUint16(10,32,true);v.setUint32(12,bytes.length,true);v.setUint32(16,22,true);u.set(bytes,22);return new Blob([b],{type:'image/x-icon'})}
async function makeSvg(c){const png=await new Promise(r=>c.toBlob(r,'image/png'));if(!png)throw Error('SVG payload encoding failed.');const bytes=new Uint8Array(await png.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return new Blob([`<svg xmlns="http://www.w3.org/2000/svg" width="${c.width}" height="${c.height}" viewBox="0 0 ${c.width} ${c.height}"><image width="${c.width}" height="${c.height}" href="data:image/png;base64,${btoa(bin)}"/></svg>`],{type:'image/svg+xml'})}
async function makePdf(c){const P=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm'),pdf=await P.PDFDocument.create(),jpg=await new Promise(r=>c.toBlob(r,'image/jpeg',.9)),img=await pdf.embedJpg(await jpg.arrayBuffer()),page=pdf.addPage([c.width,c.height]);page.drawImage(img,{x:0,y:0,width:c.width,height:c.height});return new Blob([await pdf.save()],{type:'application/pdf'})}
async function encodeCanvas(c,target){if(target==='raw'||target==='heic')throw Error(`${target.toUpperCase()} output is not supported by the browser-safe encoder yet. The source remains local and no partial file is downloaded.`);if(target==='svg')return makeSvg(c);if(target==='ico')return makeIco(c);if(target==='tiff')return encodeTiff(c);if(target==='pdf')return makePdf(c);if(!NATIVE_OUTPUT.has(target))throw Error(`Output format ${target.toUpperCase()} is unavailable in this browser-safe engine.`);const blob=await new Promise(r=>c.toBlob(r,MIME[target],.92));if(!blob)throw Error(`This browser cannot encode ${target.toUpperCase()}. Try PNG or JPG.`);return blob}
async function nativeOperation(file,name){const n=name.toLowerCase(),c=await loadImage(file),ctx=c.getContext('2d',{alpha:true});if(/grayscale|gray/.test(n))ctx.filter='grayscale(1)';else if(/sepia/.test(n))ctx.filter='sepia(1)';else if(/blur/.test(n))ctx.filter='blur(2px)';else if(/sharpen/.test(n))ctx.filter='contrast(1.08) saturate(1.05)';if(/flip.*vertical|vertical.*flip/.test(n)){const copy=document.createElement('canvas');copy.width=c.width;copy.height=c.height;copy.getContext('2d').drawImage(c,0,0);ctx.setTransform(1,0,0,-1,0,c.height);ctx.drawImage(copy,0,0);ctx.setTransform(1,0,0,1,0,0)}else if(/flip.*horizontal|horizontal.*flip/.test(n)){const copy=document.createElement('canvas');copy.width=c.width;copy.height=c.height;copy.getContext('2d').drawImage(c,0,0);ctx.setTransform(-1,0,0,1,c.width,0);ctx.drawImage(copy,0,0);ctx.setTransform(1,0,0,1,0,0)}else if(/rotate/.test(n)){const r=document.createElement('canvas');r.width=c.height;r.height=c.width;const rc=r.getContext('2d');rc.translate(r.width/2,r.height/2);rc.rotate(Math.PI/2);rc.drawImage(c,-c.width/2,-c.height/2);return r}return c}
export async function mount(slug){const app=$('#toolApp');if(!app)return;let tools=window.ZT_TOOLS;if(!tools){const base=location.pathname.startsWith('/Zero-trust/')?'/Zero-trust/':'/';const r=await fetch(base+'data/tools-index.json',{cache:'force-cache'});if(!r.ok)throw Error('Tool catalog unavailable.');tools=await r.json();window.ZT_TOOLS=tools}const meta=(tools||[]).find(x=>x.slug===slug),name=meta?.name||slug.replace(/-/g,' '),m=name.match(/^([A-Z0-9]+) to ([A-Z0-9]+) Converter$/i),converter=Boolean(m),target=m?.[2]?.toLowerCase();app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST IMAGE ENGINE · MAX 30MB · MAX 16MP · NO FILE UPLOAD</div><label for="imageFile">Choose an image</label><input id="imageFile" type="file" accept="image/*,.svg,.ico,.tif,.tiff,.heic,.heif,.raw"><button id="imageRun" class="btn primary">Run ${esc(name)}</button><div id="imageOut" class="output" role="status" aria-live="polite">Ready.</div></div>`;const f=$('#imageFile'),o=$('#imageOut');f.addEventListener('change',()=>{const file=f.files?.[0];if(file&&file.size>MAX){f.value='';out(o,'File exceeds the 30MB browser safety limit.',false)}});$('#imageRun').onclick=async()=>{try{const file=f.files?.[0];if(!file)throw Error('Choose an image.');if(file.size>MAX)throw Error('File exceeds the 30MB browser safety limit.');if(converter){const c=await loadImage(file),blob=await encodeCanvas(c,target),outExt=target==='jpeg'?'jpg':target;dl(blob,`${slug}.${outExt}`);out(o,`Converted ${file.name} → ${outExt.toUpperCase()} · ${blob.size.toLocaleString()} bytes · processed locally.`);return}const c=await nativeOperation(file,name),blob=await encodeCanvas(c,'png');dl(blob,`${slug}.png`);out(o,`Processed ${file.name} → ${c.width}×${c.height} PNG · ${blob.size.toLocaleString()} bytes · processed locally.`)}catch(e){console.error('[Zero Trust] image engine',e);out(o,e.message||'Image operation failed.',false)}}}
