const MAX=30*1024*1024;
const MAX_PIXELS=16_000_000;
const $=s=>document.querySelector(s);
const out=(o,v,ok=true)=>{o.className=`zt-output output ${ok?'success':'error'}`;o.textContent=v};
const dl=(b,n)=>{if(!b?.size)throw Error('Image operation produced an empty artifact.');const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)};
const clampCanvas=(w,h)=>{const scale=Math.min(1,Math.sqrt(MAX_PIXELS/(Math.max(1,w)*Math.max(1,h))));const c=document.createElement('canvas');c.width=Math.max(1,Math.floor(w*scale));c.height=Math.max(1,Math.floor(h*scale));return c};
async function loadNative(file){const u=URL.createObjectURL(file),im=new Image();try{im.src=u;await im.decode();const c=clampCanvas(im.naturalWidth,im.naturalHeight);c.getContext('2d',{alpha:true}).drawImage(im,0,0,c.width,c.height);return c}finally{URL.revokeObjectURL(u)}}
async function nativeOperation(file,name){const n=name.toLowerCase(),c=await loadNative(file),ctx=c.getContext('2d',{alpha:true});if(/grayscale|gray/.test(n))ctx.filter='grayscale(1)';else if(/sepia/.test(n))ctx.filter='sepia(1)';else if(/blur/.test(n))ctx.filter='blur(2px)';else if(/sharpen/.test(n))ctx.filter='contrast(1.08) saturate(1.05)';if(/flip.*vertical|vertical.*flip/.test(n)){const copy=document.createElement('canvas');copy.width=c.width;copy.height=c.height;copy.getContext('2d').drawImage(c,0,0);ctx.setTransform(1,0,0,-1,0,c.height);ctx.drawImage(copy,0,0);ctx.setTransform(1,0,0,1,0,0)}else if(/flip.*horizontal|horizontal.*flip/.test(n)){const copy=document.createElement('canvas');copy.width=c.width;copy.height=c.height;copy.getContext('2d').drawImage(c,0,0);ctx.setTransform(-1,0,0,1,c.width,0);ctx.drawImage(copy,0,0);ctx.setTransform(1,0,0,1,0,0)}else if(/rotate/.test(n)){const r=document.createElement('canvas');r.width=c.height;r.height=c.width;const rc=r.getContext('2d');rc.translate(r.width/2,r.height/2);rc.rotate(Math.PI/2);rc.drawImage(c,-c.width/2,-c.height/2);return r}else ctx.drawImage(c,0,0);return c}
async function genericConverter(file,name){const target=(name.match(/\bto\s+(jpg|jpeg|png|webp|gif|bmp|avif|pdf)\b/i)||[])[1]?.toLowerCase()||'png';const c=await loadNative(file);if(target==='pdf'){const P=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');const pdf=await P.PDFDocument.create();const jpg=await new Promise(r=>c.toBlob(r,'image/jpeg',.88));const img=await pdf.embedJpg(await jpg.arrayBuffer());const p=pdf.addPage([c.width,c.height]);p.drawImage(img,{x:0,y:0,width:c.width,height:c.height});return {blob:new Blob([await pdf.save()],{type:'application/pdf'}),ext:'pdf'}}const mime=target==='jpg'||target==='jpeg'?'image/jpeg':`image/${target}`;const blob=await new Promise(r=>c.toBlob(r,mime,.9));if(!blob)throw Error(`This browser cannot encode ${target.toUpperCase()}.`);return {blob,ext:target==='jpeg'?'jpg':target}}
export async function mount(slug){const app=$('#toolApp');if(!app)return;let tools=window.ZT_TOOLS;if(!tools){const base=location.pathname.startsWith('/Zero-trust/')?'/Zero-trust/':'/';const r=await fetch(base+'data/tools-index.json',{cache:'force-cache'});if(!r.ok)throw Error('Tool catalog unavailable.');tools=await r.json();window.ZT_TOOLS=tools}const meta=(tools||[]).find(x=>x.slug===slug),name=meta?.name||slug.replace(/-/g,' '),n=name.toLowerCase(),converter=/\bto\s+(jpg|jpeg|png|webp|gif|bmp|avif|pdf)\b/i.test(name);app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST IMAGE ENGINE — 30MB input cap, 16MP working canvas</div><input id="imageFile" type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.gif,.bmp,.avif"><button id="imageRun" class="btn primary">Run</button><div id="imageOut" class="output">Ready.</div></div>`;const f=$('#imageFile'),o=$('#imageOut');f.addEventListener('change',()=>{const file=f.files[0];if(file&&file.size>MAX){f.value='';out(o,'File exceeds the 30MB browser safety limit.',false)}});$('#imageRun').onclick=async()=>{try{const file=f.files[0];if(!file)throw Error('Choose an image.');if(file.size>MAX)throw Error('File exceeds the 30MB browser safety limit.');if(converter){const r=await genericConverter(file,name);dl(r.blob,`${slug}.${r.ext}`);out(o,`Converted ${file.name} → ${r.ext.toUpperCase()} · ${r.blob.size.toLocaleString()} bytes`);return}const c=await nativeOperation(file,name);const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('Browser image encoder failed.');dl(blob,`${slug}.png`);out(o,`Processed ${file.name} → ${c.width}×${c.height} PNG · ${blob.size.toLocaleString()} bytes`)}catch(e){console.error('[Zero Trust] image engine',e);out(o,e.message||'Image operation failed.',false)}}}