const words=s=>String(s??'').trim().match(/[\p{L}\p{N}]+(?:['’.-][\p{L}\p{N}]+)*/gu)||[];
const tokens=s=>String(s??'').trim().split(/[^A-Za-z0-9]+/).filter(Boolean);
export const camel=s=>{const a=tokens(s);return a.map((x,i)=>i?x[0].toUpperCase()+x.slice(1).toLowerCase():x.toLowerCase()).join('')};
export const pascal=s=>{const x=camel(s);return x?x[0].toUpperCase()+x.slice(1):x};
export const snake=s=>tokens(s).map(x=>x.toLowerCase()).join('_');export const kebab=s=>tokens(s).map(x=>x.toLowerCase()).join('-');
export const title=s=>String(s).toLowerCase().replace(/\b[\p{L}\p{N}]/gu,c=>c.toUpperCase());
export const sentence=s=>{const x=String(s).toLowerCase().trim();return x.replace(/(^|[.!?]\s+)([\p{L}])/gu,(_,p,c)=>p+c.toUpperCase())};
export const counts=s=>{const x=String(s??'');return{characters:x.length,charactersNoSpaces:x.replace(/\s/g,'').length,words:words(x).length,lines:x?x.split(/\r?\n/).length:0,readingTimeMinutes:Math.max(1,Math.ceil(words(x).length/200))}};
export const sortLines=(s,numeric=false)=>String(s??'').split(/\r?\n/).sort((a,b)=>numeric?(parseFloat(a)-parseFloat(b))||a.localeCompare(b):a.localeCompare(b)).join('\n');
export const uniqueLines=s=>[...new Set(String(s??'').split(/\r?\n/))].join('\n');export const stripWhitespace=s=>String(s??'').replace(/\s+/g,' ').trim();export const stripNewlines=s=>String(s??'').replace(/[\r\n]+/g,' ');
export function levenshtein(a,b){a=String(a);b=String(b);let p=Array(b.length+1).fill(0);for(let j=0;j<=b.length;j++)p[j]=j;for(let i=1;i<=a.length;i++){const c=[i];for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=c}return p[b.length]}
export function diff(a,b){const A=String(a).split(/\r?\n/),B=String(b).split(/\r?\n/),out=[];let i=0,j=0;while(i<A.length||j<B.length){if(A[i]===B[j]){if(i<A.length)out.push({type:'equal',value:A[i]});i++;j++}else if(j<B.length&&!A.slice(i,i+3).includes(B[j]))out.push({type:'added',value:B[j++]});else out.push({type:'removed',value:A[i++]})}return out}
const ops={camel,pascal,snake,kebab,title,sentence,counts,sortLines,uniqueLines,stripWhitespace,stripNewlines};
export function mount(slug){const s=slug.toLowerCase();const op=Object.keys(ops).find(k=>s.includes(k.replace('strip','strip-'))||s.includes(k));if(!op)throw Error(`No text operation mapped for ${slug}.`);const app=document.querySelector('#toolApp');app.innerHTML=`<div class="zt-card"><div class="zt-local">LOCAL-FIRST · text engine</div><textarea id="tx" rows="10" placeholder="Enter text…"></textarea><button class="btn primary" id="tr">Process</button><pre class="output" id="to">Ready.</pre></div>`;document.querySelector('#tr').onclick=()=>{try{const r=ops[op](document.querySelector('#tx').value);document.querySelector('#to').textContent=typeof r==='object'?JSON.stringify(r,null,2):r;document.querySelector('#to').className='output success'}catch(e){document.querySelector('#to').textContent=e.message;document.querySelector('#to').className='output error'}}}
