const base=process.env.API_BASE||'http://127.0.0.1:8787';const ownerEmail=process.env.TEST_OWNER_EMAIL,ownerPassword=process.env.TEST_OWNER_PASSWORD,secret=process.env.TEST_OWNER_BOOTSTRAP_SECRET;if(!ownerEmail||!ownerPassword||!secret)throw Error('API smoke environment is incomplete');
async function req(path,opts={}){const r=await fetch(base+path,{...opts,headers:{'content-type':'application/json',...(opts.headers||{})}});const text=await r.text();let data={};try{data=JSON.parse(text)}catch{}if(!r.ok)throw Error(`${path} ${r.status}: ${data.error||text}`);return{r,data}}
const boot=await req('/api/owner/bootstrap',{method:'POST',headers:{'x-owner-bootstrap':secret},body:JSON.stringify({email:ownerEmail,password:ownerPassword})});if(!boot.data.ok)throw Error('Owner bootstrap failed');
const login=await req('/api/auth/login',{method:'POST',body:JSON.stringify({email:ownerEmail,password:ownerPassword})});const cookie=login.r.headers.get('set-cookie');if(!cookie||!login.data.csrfToken)throw Error('Secure owner session was not issued');
const me=await req('/api/me',{headers:{cookie}});if(!me.data.authenticated||me.data.user.role!=='owner')throw Error('Owner session authorization failed');
const overview=await req('/api/owner/overview',{headers:{cookie}});if(typeof overview.data.users!=='number')throw Error('Owner overview failed');
await req('/api/owner/settings',{method:'POST',headers:{cookie,'x-csrf-token':login.data.csrfToken},body:JSON.stringify({key:'maintenance_mode',value:'false'})});
await req('/api/owner/tools/api-smoke-tool',{method:'POST',headers:{cookie,'x-csrf-token':login.data.csrfToken},body:JSON.stringify({requiredPlan:'pro',enabled:true})});
const gated=await req('/api/tools/api-smoke-tool',{headers:{cookie}});if(!gated.data.allowed||gated.data.plan!=='pro')throw Error('Server-side Pro entitlement failed');
const userEmail=process.env.TEST_USER_EMAIL,userPassword=process.env.TEST_USER_PASSWORD;const user=await req('/api/auth/signup',{method:'POST',body:JSON.stringify({email:userEmail,password:userPassword,first_name:'CI',last_name:'User',display_name:'CI User',country:'India',timezone:'Asia/Kolkata',locale:'en-IN',terms_accepted:true,privacy_accepted:true,marketing_opt_in:false})});if(!user.data.ok)throw Error('User signup failed');if(!user.data.csrfToken)throw Error('Signup session missing CSRF token');const userCookie=user.r.headers.get('set-cookie');const profile=await req('/api/account/profile',{headers:{cookie:userCookie}});if(profile.data.profile?.first_name!=='CI')throw Error('Profile onboarding failed');await req('/api/account/profile',{method:'PATCH',headers:{cookie:userCookie,'x-csrf-token':user.data.csrfToken},body:JSON.stringify({first_name:'CI',last_name:'Updated',display_name:'CI Updated',country:'India',timezone:'Asia/Kolkata',locale:'en-IN',marketing_opt_in:false})});
await req('/api/auth/logout',{method:'POST',headers:{cookie:userCookie}});await req('/api/auth/logout',{method:'POST',headers:{cookie}});console.log('PASS: D1 signup/login/session, profile onboarding/update, owner authorization, CSRF actions, entitlement enforcement and logout verified.');
