import{chromium}from'playwright';
import fs from'node:fs';
import vm from'node:vm';
const source=fs.readFileSync('app.js','utf8');const ctx={window:{},document:{addEventListener(){}}};vm.runInNewContext(source,ctx,{filename:'app.js'});const routes=ctx.window.ZT_TOOLS||[];if(routes.length<500)throw new Error(`Expected 500+ routes, found ${routes.length}`);
const deploy=fs.readFileSync('.github/workflows/pages.yml','utf8');if(!deploy.includes('Generate 500+ SEO tool pages'))throw new Error('SEO page generation missing');if(!deploy.includes('Normalize physical tool bootstraps'))throw new Error('Bootstrap normalization missing');
for(const [slug] of routes){if(!fs.existsSync(`tools/${slug}/index.html`))throw new Error(`Generated route missing: ${slug}`);const html=fs.readFileSync(`tools/${slug}/index.html`,'utf8');if(!/robots" content="index,follow"/.test(html)||!html.includes(`tools/${slug}/`))throw new Error(`SEO metadata missing: ${slug}`)}
const browser=await chromium.launch({headless:true});
const sample=routes.filter((_,i)=>i<80||i%13===0).map(x=>x[0]);
const workers=Array.from({length:6},async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});for(const slug of sample.splice(0,20)){await page.goto(`http://127.0.0.1:4173/Zero-trust/tools/${slug}/`,{waitUntil:'domcontentloaded',timeout:15000});await page.waitForSelector('#toolApp .tool-box',{timeout:7000});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);if(overflow)throw new Error(`Horizontal overflow: ${slug}`);const text=await page.locator('#toolApp').innerText();if(/could not load|failed to load/i.test(text))throw new Error(`Engine failed: ${slug}`)}await page.close()});await Promise.all(workers);
const page=await browser.newPage({viewport:{width:390,height:844}});await page.goto('http://127.0.0.1:4173/Zero-trust/tools/',{waitUntil:'domcontentloaded'});await page.locator('#toolSearch').fill('PDF');if(await page.locator('#allTools .tool-card').count()<100)throw new Error('PDF search did not expose 100+ tools');await page.locator('#categoryFilter').selectOption('pdf');if(await page.locator('#allTools .tool-card').count()<100)throw new Error('PDF category filter did not expose 100+ tools');await page.locator('#menuBtn').click();if(!(await page.locator('#mobileNav').getAttribute('data-open')))throw new Error('Mobile navigation failed');
const pdfBytes=await page.evaluate(async()=>{const{PDFDocument}=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');const d=await PDFDocument.create();const f=await d.embedFont('Helvetica');for(let i=1;i<=3;i++){const p=d.addPage([400,300]);p.drawText(`Smoke test page ${i}`,{x:40,y:250,size:18,font:f})}return Array.from(await d.save())});
async function upload(bytes,name='smoke.pdf'){await page.locator('#file').setInputFiles({name,mimeType:'application/pdf',buffer:Buffer.from(bytes)})}
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-count/');await upload(pdfBytes);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('3 page'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-duplicate/');await upload(pdfBytes);await page.locator('#pages').fill('2');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('duplicated'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-delete-range/');await upload(pdfBytes);await page.locator('#pages').fill('2');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Created 2'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-number-overlay/');await upload(pdfBytes);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Applied 3'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-text-search/');await upload(pdfBytes);await page.locator('#query').fill('Smoke test page 2');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Page 2'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-to-png-all/');await upload(pdfBytes);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Rendered 3'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/password-generator/');await page.locator('#run').click();if((await page.locator('#outText').inputValue()).length<8)throw new Error('Password generator action failed');
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/secure-random-generator/');await page.locator('#run').click();if(!(await page.locator('#outText').inputValue()).length)throw new Error('Secure random generator action failed');
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/json-formatter/');await page.locator('#input').fill('{"a":1}');await page.locator('#format').click();if(!(await page.locator('#out').innerText()).includes('"a": 1'))throw new Error('JSON formatter action failed');
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/base64-decoder/');await page.locator('#input').fill('SGVsbG8=');await page.locator('#decode').click();if((await page.locator('#out').innerText()).trim()!=='Hello')throw new Error('Base64 decoder action failed');
await page.close();await browser.close();console.log(`Browser smoke passed: ${routes.length} route files audited, representative engines executed, mobile overflow/navigation checked, search/filter/SEO validated, and key PDF/security/developer actions passed`);