import{chromium}from'playwright';
import fs from'node:fs';
import vm from'node:vm';
const source=fs.readFileSync('app.js','utf8');const ctx={window:{},document:{addEventListener(){}}};vm.runInNewContext(source,ctx,{filename:'app.js'});const routes=ctx.window.ZT_TOOLS||[];if(routes.length<500)throw new Error(`Expected 500+ routes, found ${routes.length}`);
const deploy=fs.readFileSync('.github/workflows/pages.yml','utf8');if(!deploy.includes('Generate 500+ SEO tool pages'))throw new Error('SEO page generation missing');if(!deploy.includes('Normalize physical tool bootstraps'))throw new Error('Bootstrap normalization missing');if(!deploy.includes('cloudflare/wrangler-action'))throw new Error('Cloudflare deployment missing');
for(const [slug]of routes){const file=`tools/${slug}/index.html`;if(!fs.existsSync(file))throw new Error(`Generated route missing: ${slug}`);const html=fs.readFileSync(file,'utf8');if(!/<meta\s+name=["']robots["'][^>]*content=["'][^"']*index,follow/i.test(html)||!html.includes(`tools/${slug}/`))throw new Error(`SEO metadata missing: ${slug}`);if(!/<h1[^>]*id=["']toolTitle["']/i.test(html)||!/<div[^>]*id=["']toolApp["']/i.test(html))throw new Error(`Tool runtime shell missing: ${slug}`)}
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
async function route(slug){errors=[];await page.goto(`http://127.0.0.1:4173/Zero-trust/tools/${slug}/`,{waitUntil:'domcontentloaded',timeout:15000});await page.waitForSelector('#toolApp',{timeout:10000});await page.waitForSelector('#toolTitle',{timeout:10000});try{await page.waitForFunction(()=>{const app=document.querySelector('#toolApp');if(!app)return false;return !!app.querySelector('button,input,textarea,select,[contenteditable="true"]')&&!/Loading\.\.\.|Tool engine failed to load|Tool failed to load/i.test(app.innerText)},{timeout:15000})}catch(e){const body=(await page.locator('#toolApp').innerText().catch(()=>'' )).slice(0,500);throw new Error(`Tool did not mount: ${slug}; body=${body}; pageErrors=${errors.join('; ')}`)}const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);if(overflow)throw new Error(`Horizontal overflow: ${slug}`);if((await page.locator('#toolTitle').innerText()).includes('Loading'))throw new Error(`Tool title did not hydrate: ${slug}`);if((await page.locator('#toolApp').innerText()).includes('Tool engine failed to load'))throw new Error(`Engine failed: ${slug}`);if(errors.length)throw new Error(`Browser error on ${slug}: ${errors.join('; ')}`)}
const picked=[routes[0][0],routes.find(x=>x[2]==='pdf')?.[0],routes.find(x=>x[2]==='image')?.[0],routes.find(x=>x[2]==='qr')?.[0],routes.find(x=>x[2]==='security')?.[0],routes.find(x=>x[2]==='developer')?.[0],routes.find(x=>x[2]==='text')?.[0],routes.find(x=>x[2]==='calculator')?.[0],'pdf-page-count','pdf-page-duplicate','pdf-page-delete-range','pdf-page-number-overlay','pdf-text-search','pdf-to-png-all','password-generator','secure-random-generator','json-formatter','base64-decoder','image-compress-quick','image-resize-batch','qr-url-quick','security-random-quick','calculator-percentage-basic','developer-format-quick','text-count-quick','pdf-merge-quick','pdf-inspect-advanced'].filter(Boolean);for(const slug of [...new Set(picked)])await route(slug);
const pdfBytes=await page.evaluate(async()=>{const{PDFDocument}=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');const d=await PDFDocument.create();const f=await d.embedFont('Helvetica');for(let i=1;i<=3;i++){const p=d.addPage([400,300]);p.drawText(`Smoke test page ${i}`,{x:40,y:250,size:18,font:f})}return Array.from(await d.save())});async function upload(bytes,name='smoke.pdf'){await page.locator('#file').setInputFiles({name,mimeType:'application/pdf',buffer:Buffer.from(bytes)})}
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-count/');await upload(pdfBytes);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('3 page'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-duplicate/');await upload(pdfBytes);await page.locator('#pages').fill('2');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Duplicated'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-delete-range/');await upload(pdfBytes);await page.locator('#pages').fill('2');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Created 2'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-page-number-overlay/');await upload(pdfBytes);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Applied to 3'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-text-search/');await upload(pdfBytes);await page.locator('#query').fill('Smoke test page 2');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Page 2'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-to-png-all/');await upload(pdfBytes);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Rendered 3'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/pdf-merge-quick/');await page.locator('#file').setInputFiles([{name:'a.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdfBytes)},{name:'b.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdfBytes)}]);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Created 6'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/image-compress-quick/');const png=await page.evaluate(()=>new Promise(r=>{const c=document.createElement('canvas');c.width=100;c.height=80;c.getContext('2d').fillRect(0,0,100,80);c.toBlob(b=>b.arrayBuffer().then(x=>r(Array.from(new Uint8Array(x)))),'image/png')}));await page.locator('#file').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from(png)});await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.dataset.status==='success');
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/text-count-quick/');await page.locator('#input').fill('one two three');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Words: 3'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/developer-format-quick/');await page.locator('#input').fill('{"a":1}');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('"a": 1'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/calculator-percentage-basic/');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('10'));
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/security-random-quick/');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.dataset.status==='success');
await page.goto('http://127.0.0.1:4173/Zero-trust/tools/qr-url-quick/');await page.locator('#input').fill('https://example.com');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status')?.dataset.status==='success');
await page.goto('http://127.0.0.1:4173/Zero-trust/');if(await page.locator('#featured .tool-card').count()<8)throw new Error('Home featured tools missing');await page.goto('http://127.0.0.1:4173/Zero-trust/tools/');await page.locator('#toolSearch').fill('PDF');if(await page.locator('#allTools .tool-card').count()<100)throw new Error('PDF search did not expose 100+ tools');await page.locator('#categoryFilter').selectOption('pdf');if(await page.locator('#allTools .tool-card').count()<100)throw new Error('PDF category filter did not expose 100+ tools');await page.locator('#menuBtn').click();if(!(await page.locator('#mobileNav').evaluate(el=>el.hasAttribute('data-open'))))throw new Error('Mobile navigation failed');
await page.close();await browser.close();console.log(`Browser smoke passed: ${routes.length} routes statically audited, generated PDF/image/QR/security/developer/text/calculator routes executed, core PDF actions executed, mobile overflow/navigation checked, search/filter tested, and functional outputs verified`);