import fs from 'node:fs';
import path from 'node:path';
import { CATALOG } from '../data/catalog-combined.mjs';

const root=process.cwd();
const outputRoot=process.env.OUT_DIR?path.join(root,process.env.OUT_DIR):root;
const tools=CATALOG;
if(tools.length!==1594) throw new Error(`Combined catalog integrity failure: expected 1594 tools, found ${tools.length}`);
const categories=[...new Map(tools.map(t=>[t.category,{slug:t.category,name:t.categoryName,count:0}])).values()];
for(const t of tools)categories.find(c=>c.slug===t.category).count++;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const BASE=process.env.SITE_BASE||'/';
const abs=p=>`${BASE}${p}`.replace(/\/+/g,'/');
const nav=`<header class="site-header"><a class="brand" href="${abs('')}" aria-label="Zero Trust home"><span class="brand-mark" aria-hidden="true">ZT</span><span class="brand-name">Zero Trust</span></a><nav><a class="nav-link" href="${abs('tools/')}">All tools</a><a class="nav-link" href="${abs('security/')}">Security</a><button id="themeBtn" class="icon-btn" type="button">Dark</button><button id="menuBtn" class="icon-btn mobile-menu" type="button" aria-expanded="false">Menu</button></nav></header>`;
const footer=`<footer><span>© 2026 Zero Trust</span><span><a href="${abs('privacy/')}">Privacy</a> · <a href="${abs('security/')}">Security</a> · <a href="${abs('accessibility/')}">Accessibility</a></span></footer>`;
const shell=(title,description,body,canonical)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${abs(canonical)}"><link rel="stylesheet" href="${abs('styles.css')}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:title,applicationCategory:'UtilitiesApplication',operatingSystem:'Any',description})}</script></head><body>${nav}<main>${body}</main>${footer}<script src="${abs('app.js?v=304')}" defer></script>${canonical.startsWith('tools/')&&!canonical.includes('category/')?`<script type="module" src="${abs('tool-engine.js?v=304')}"></script>`:''}</body></html>`;
const write=(rel,html)=>{const f=path.join(outputRoot,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,html)};
const card=t=>`<a class="tool-card" href="${abs(`tools/${t.slug}/`)}"><span class="eyebrow">${esc(t.categoryName)}</span><h3>${esc(t.name)}</h3><p>Real browser tool · ${t.phase===1?'local-first':'network-dependent capability'}</p></a>`;
for(const t of tools){const related=tools.filter(x=>x.category===t.category&&x.slug!==t.slug).slice(0,6);const desc=`${t.name}: a practical Zero Trust browser utility. Process supported input locally when technically possible, review the result, and download or copy the output.`;const body=`<section class="tool-shell"><div class="breadcrumbs"><a href="${abs('tools/')}">All tools</a> / <a href="${abs(`tools/category/${t.category}/`)}">${esc(t.categoryName)}</a> / ${esc(t.name)}</div><div class="eyebrow">${esc(t.categoryName).toUpperCase()}</div><h1 id="toolTitle">${esc(t.name)}</h1><p id="toolDesc">${esc(desc)}</p><div class="privacy-badge">${t.phase===1?'LOCAL-FIRST — INPUT STAYS IN THIS BROWSER':'NETWORK CAPABILITY — REQUESTS ARE DISCLOSED'}</div><div id="toolApp" data-engine="${esc(t.engine)}"></div><section class="content-section"><h2>How to use</h2><ol><li>Provide the input requested by the tool.</li><li>Run the operation and inspect the result.</li><li>Download or copy the result when it is correct.</li></ol><h2>Privacy</h2><p>${t.phase===1?'This tool is designed for local browser processing. Your input is not uploaded by the page as part of the core operation.':'This tool may require network access. The interface identifies that requirement.'}</p><h2>FAQ</h2><h3>Is this tool free?</h3><p>Yes. The page is available without an account.</p><h3>Are my files uploaded?</h3><p>Client-side tools process files in this browser. Network-dependent tools are identified.</p></section></section><section class="section related-section"><div class="section-head"><div><div class="eyebrow">RELATED</div><h2>More ${esc(t.categoryName)}</h2></div><a href="${abs(`tools/category/${t.category}/`)}">View category</a></div><div class="tool-grid">${related.map(card).join('')}</div></section>`;write(`tools/${t.slug}/index.html`,shell(`${t.name} — Zero Trust`,desc,body,`tools/${t.slug}/`))}
for(const c of categories){const items=tools.filter(t=>t.category===c.slug);const body=`<section class="page"><div class="eyebrow">CATEGORY</div><h1>${esc(c.name)}</h1><p>${c.count} tools in this category, with static HTML content and browser runtime enhancement.</p><div class="tool-grid">${items.map(card).join('')}</div></section>`;write(`tools/category/${c.slug}/index.html`,shell(`${c.name} — Zero Trust`,`Browse ${c.count} ${c.name} tools.`,body,`tools/category/${c.slug}/`))}
const indexBody=`<section class="page"><div class="eyebrow">ZERO TRUST TOOL DIRECTORY</div><h1>All ${tools.length} tools</h1><p>Search and filter the complete directory. Every entry has a real tool page and a declared processing engine.</p><div class="tool-filters"><input class="tools-search" id="toolSearch" placeholder="Search tools…" autocomplete="off"><select class="tools-search" id="categoryFilter"><option value="">All categories</option>${categories.map(c=>`<option value="${esc(c.slug)}">${esc(c.name)}</option>`).join('')}</select></div><div class="small" id="toolCount">${tools.length} tools</div><div class="tool-grid" id="allTools">${tools.map(card).join('')}</div></section>`;
write('tools/index.html',shell(`All ${tools.length} tools — Zero Trust`,`Browse all ${tools.length} Zero Trust browser tools.`,indexBody,'tools/'));
const homeBody=`<section class="hero"><div class="eyebrow">PRIVATE BY DEFAULT · LOCAL-FIRST · NO ACCOUNT</div><h1>Your everyday tools.<br><span>Without sending your files away.</span></h1><p>Real browser utilities for documents, images, data, code, text and more. Input stays local for client-side tools whenever technically possible.</p><div class="hero-actions"><a class="btn primary" href="${abs('tools/')}">Explore ${tools.length} tools</a><a class="btn" href="${abs('tools/category/pdf-utility-tools/')}">Open PDF tools</a></div><div class="status">Local-first processing where supported.</div></section><section class="section"><div class="section-head"><div><div class="eyebrow">START HERE</div><h2>Useful tools, zero clutter.</h2></div><a href="${abs('tools/')}">View all</a></div><div class="tool-grid">${tools.slice(0,12).map(card).join('')}</div></section><section class="section"><div class="section-head"><div><div class="eyebrow">CATEGORIES</div><h2>Find the right tool.</h2></div></div><div class="tool-grid">${categories.map(c=>`<a class="tool-card" href="${abs(`tools/category/${c.slug}/`)}"><span class="eyebrow">${c.count} tools</span><h3>${esc(c.name)}</h3><p>Browse the complete category.</p></a>`).join('')}</div></section>`;
write('index.html',shell('Zero Trust — Private Browser Tools',`${tools.length} privacy-first browser tools for files, text, data, developer workflows and calculations.`,homeBody,''));
write('data/tools-index.json',JSON.stringify(tools));write('data/categories.json',JSON.stringify(categories));write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${abs('sitemap.xml')}\n`);const urls=[abs(''),abs('tools/'),...tools.map(t=>abs(`tools/${t.slug}/`)),...categories.map(c=>abs(`tools/category/${c.slug}/`))];write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);console.log(`Generated ${tools.length} tool pages, ${categories.length} category pages into ${outputRoot}.`);