import platform from './platform-router.mjs';
import { CATALOG } from '../data/catalog-combined.mjs';
import { handleProxy } from './proxy.mjs';
const json=(d,status=200)=>new Response(JSON.stringify(d),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const secure=r=>{const h=new Headers(r.headers);h.set('Cross-Origin-Opener-Policy','same-origin');h.set('Cross-Origin-Embedder-Policy','require-corp');h.set('Cross-Origin-Resource-Policy','cross-origin');h.set('X-Content-Type-Options','nosniff');return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})};
const cookies=r=>Object.fromEntries((r.headers.get('Cookie')||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));
async function hash(s){const a=new TextEncoder().encode(s),h=await crypto.subtle.digest('SHA-256',a);return btoa(String.fromCharCode(...new Uint8Array(h))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function gate(req,env,slug){const meta=CATALOG.find(x=>x.slug===slug);if(!meta)return json({allowed:false,reason:'unknown_tool'},404);const row=env.DB?await env.DB.prepare('SELECT required_plan,enabled FROM tool_entitlements WHERE slug=?').bind(slug).first():null;if(row&&!row.enabled)return json({allowed:false,reason:'disabled'},403);const required=row?.required_plan||(meta.phase===2?'pro':'free');if(required==='pro'){const raw=cookies(req).zt_session;if(!raw)return json({allowed:false,reason:'pro_required'},403);const s=await env.DB?.prepare('SELECT u.plan,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await hash(raw),new Date().toISOString()).first();if(!s||s.status!=='active'||s.plan!=='pro')return json({allowed:false,reason:'pro_required'},403);return json({allowed:true,plan:'pro',requiredPlan:'pro'})}return json({allowed:true,plan:'free',requiredPlan:'free'})}
export default{async fetch(req,env,ctx){const p=new URL(req.url).pathname.replace(/^\/Zero-trust/,'');if(p.startsWith('/api/tools/')&&req.method==='GET')return secure(await gate(req,env,p.slice('/api/tools/'.length)));if(p==='/api/proxy'&&req.method==='GET'){const slug=new URL(req.url).searchParams.get('tool')||'';const meta=CATALOG.find(x=>x.slug===slug);if(!meta||!['network','seo'].includes(meta.engine)||meta.phase!==2)return secure(json({error:'This relay is reserved for supported Pro network/SEO tools.'},403));const g=await gate(req,env,slug);const gd=await g.clone().json().catch(()=>({}));if(gd.allowed!==true)return secure(g);return secure(await handleProxy(req,env))}return secure(await platform.fetch(req,env,ctx))}};
