const MAX=2*1024*1024;
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const blockedHost=h=>{h=h.toLowerCase().replace(/\.$/,'');return h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.home.arpa')||h==='0.0.0.0'||h==='127.0.0.1'||h==='::1'||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[0-1])\./.test(h)||/^\[?f[cd][0-9a-f:]*\]?$/i.test(h)||/^\[?fe8[0-9a-f:]*\]?$/i.test(h)};
const validUrl=value=>{let u;try{u=new URL(value)}catch{throw Error('Enter a valid URL.')}if(!/^https?:$/u.test(u.protocol)||blockedHost(u.hostname))throw Error('Only public HTTP(S) targets are allowed.');u.username='';u.password='';return u};
async function safeFetch(value,init={},maxRedirects=5){let u=validUrl(value);for(let i=0;i<=maxRedirects;i++){const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);try{const r=await fetch(u,{...init,redirect:'manual',signal:c.signal});if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get('location');if(!loc)throw Error('Target returned a redirect without a location.');u=new URL(loc,u);if(blockedHost(u.hostname))throw Error('Redirected target is not public.');continue}return r}finally{clearTimeout(timer)}}throw Error('Too many redirects.')}
async function readLimited(r){const len=Number(r.headers.get('content-length')||0);if(len>MAX)throw Error('Target response exceeds the 2MB safety limit.');const reader=r.body?.getReader();if(!reader)return await r.text();const chunks=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>MAX){await reader.cancel();throw Error('Target response exceeds the 2MB safety limit.')}chunks.push(value)}const b=new Uint8Array(total);let p=0;for(const c of chunks){b.set(c,p);p+=c.byteLength}return new TextDecoder().decode(b)}
const textLinks=(html,base)=>[...html.matchAll(/(?:href|src)\s*=\s*["']([^"']+)["']/giu)].map(m=>{try{return new URL(m[1],base).href}catch{return null}}).filter(u=>{try{return /^https?:$/u.test(new URL(u).protocol)}catch{return false}});
const publicHost=target=>{const host=target.includes('://')?validUrl(target).hostname:target.trim();if(!/^[a-z0-9.-]+$/iu.test(host)||blockedHost(host))throw Error('Enter a public hostname.');return host};
export async function handleProxy(req,env){const url=new URL(req.url);if(req.method!=='GET')return json({error:'GET only'},405);const op=url.searchParams.get('op')||'fetch',target=url.searchParams.get('target')||'',q=url.searchParams.get('q')||'';try{
if(op==='ip')return json({ip:req.headers.get('CF-Connecting-IP')||null,country:req.headers.get('CF-IPCountry')||null,colo:req.cf?.colo||null,asn:req.cf?.asn||null});
if(op==='dns'){const host=publicHost(target),type=/^(A|AAAA|MX|TXT|CNAME|NS)$/u.test(q)?q:'A';const r=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(host)}&type=${type}`,{headers:{accept:'application/dns-json'},signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('DNS provider request failed.');return json(await r.json())}
if(op==='whois')return json({supported:false,message:'WHOIS registry data is provider-specific; DNS and HTTP inspection are available without exposing raw socket access.'},501);
const u=validUrl(target);
if(op==='port'){const port=Math.max(1,Math.min(65535,Number(q)||443));const start=performance.now();const r=await safeFetch(`${u.protocol==='https:'?'https':'http'}://${u.hostname}:${port}/`,{method:'HEAD'},0);return json({host:u.hostname,port,protocol:u.protocol,status:r.status,reachable:true,latencyMs:Math.round(performance.now()-start)})}
if(op==='ping'){const start=performance.now();const r=await safeFetch(u,{method:'HEAD'},0);return json({target:u.href,reachable:r.ok||r.status<500,status:r.status,latencyMs:Math.round(performance.now()-start),mode:'HTTP reachability (browser-safe; not ICMP)'})}
if(op==='traceroute'){const hops=[];let current=u.href;for(let i=0;i<5;i++){const start=performance.now(),r=await safeFetch(current,{method:'HEAD'},0);hops.push({hop:i+1,url:current,status:r.status,latencyMs:Math.round(performance.now()-start)});const loc=r.headers.get('location');if(!loc)break;current=new URL(loc,current).href}return json({target:u.href,hops,mode:'HTTP redirect-chain trace; not raw ICMP traceroute'})}
const start=performance.now(),r=await safeFetch(u);const headers=Object.fromEntries([...r.headers.entries()]);if(op==='headers'||op==='ssl')return json({url:u.href,status:r.status,headers});
if(op==='robots'){const ru=new URL('/robots.txt',u);const rr=await safeFetch(ru);return json({url:rr.url,status:rr.status,text:(await readLimited(rr)).slice(0,200000)})}
const html=await readLimited(r);
if(op==='opengraph')return json({url:u.href,status:r.status,title:(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'',tags:[...html.matchAll(/<meta[^>]+(?:property|name)=["']([^"']+)["'][^>]+content=["']([^"']*)["'][^>]*>/giu)].slice(0,100).map(m=>({name:m[1],content:m[2]}))});
if(op==='links'){const links=[...new Set(textLinks(html,u.href))].slice(0,100),results=[];for(let i=0;i<links.length;i+=10){const rows=await Promise.all(links.slice(i,i+10).map(async link=>{try{const x=await safeFetch(link,{method:'HEAD'},0);return{url:link,status:x.status,ok:x.ok}}catch(e){return{url:link,status:0,ok:false,error:e.message}}}));results.push(...rows)}return json({source:u.href,total:results.length,broken:results.filter(x=>!x.ok),results})}
if(op==='redirects')return json({url:u.href,status:r.status,finalUrl:r.url,redirected:r.redirected,headers});
if(op==='speed')return json({url:u.href,status:r.status,bytes:new TextEncoder().encode(html).byteLength,elapsedMs:Math.round(performance.now()-start),contentType:r.headers.get('content-type')||'',note:'Server-side HTTP timing; not a full Lighthouse/browser performance score.'});
return json({url:u.href,status:r.status,contentType:r.headers.get('content-type')||'',bytes:new TextEncoder().encode(html).byteLength,preview:html.slice(0,4000)})
}catch(e){return json({error:e.name==='AbortError'?'Target request timed out':e.message||'Proxy request failed'},400)}}
