const enc=new TextEncoder(),DAYS=7,ITER=210000;
const out=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}});
const t=()=>new Date().toISOString(),uid=()=>crypto.randomUUID(),rnd=n=>crypto.getRandomValues(new Uint8Array(n));
const b64=a=>btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
async function hash(s){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
async function pw(password,salt){const raw=salt?unb64(salt):rnd(16),k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:raw,iterations:ITER,hash:'SHA-256'},k,256);return{salt:b64(raw),hash:b64(new Uint8Array(bits))}}
const ip=req=>req.headers.get('CF-Connecting-IP')||'unknown';
const parseCookies=req=>Object.fromEntries((req.headers.get('Cookie')||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));
const sessionCookie=(v,max)=>`zt_session=${encodeURIComponent(v)}; Path=/; Max-Age=${max}; HttpOnly; Secure; SameSite=Strict`;
async function body(req){try{return await req.json()}catch{return null}}
function headers(){return{'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy':'same-origin','content-security-policy':"default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'"}}
async function rate(env,key,limit=12){if(!env.DB)return true;const r=await env.DB.prepare('SELECT * FROM login_attempts WHERE key=?').bind(key).first(),n=Date.now();if(!r||n-Date.parse(r.window_started_at)>900000){await env.DB.prepare('INSERT OR REPLACE INTO login_attempts(key,window_started_at,attempts,blocked_until) VALUES(?,?,0,NULL)').bind(key,t()).run();return true}return !r.blocked_until||Date.parse(r.blocked_until)<=n?r.attempts<limit:false}
async function attempt(env,key,failed){if(!env.DB)return;const r=await env.DB.prepare('SELECT * FROM login_attempts WHERE key=?').bind(key).first(),n=(r?.attempts||0)+(failed?1:0);if(!failed){await env.DB.prepare('DELETE FROM login_attempts WHERE key=?').bind(key).run();return}await env.DB.prepare('INSERT OR REPLACE INTO login_attempts(key,window_started_at,attempts,blocked_until) VALUES(?,?,?,?)').bind(key,r?.window_started_at||t(),n,n>=12?new Date(Date.now()+1800000).toISOString():null).run()}
async function sess(req,env){if(!env.DB)return null;const raw=parseCookies(req).zt_session;if(!raw)return null;return env.DB.prepare('SELECT s.*,u.email,u.role,u.plan,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await hash(raw),t()).first()}
async function owner(req,env){const s=await sess(req,env);if(!s)return{r:out({error:'Authentication required'},401)};if(s.role!=='owner')return{r:out({error:'Owner access required'},403)};return{s}}
async function csrf(req,s){return req.headers.get('x-csrf-token')===s.csrf_token}
async function audit(env,s,action,targetType='',targetId='',meta={}){if(!env.DB)return;await env.DB.prepare('INSERT INTO audit_log(actor_user_id,action,target_type,target_id,metadata_json,created_at,ip_hash) VALUES(?,?,?,?,?,?,?)').bind(s?.user_id||null,action,targetType,targetId,JSON.stringify(meta),t(),await hash(ip({headers:new Headers({'CF-Connecting-IP':ip})}))).run()}
async function start(req,env,id){const raw=b64(rnd(32)),csrfToken=b64(rnd(24)),created=t(),expires=new Date(Date.now()+DAYS*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,csrf_token,created_at,expires_at,last_seen_at,user_agent,ip_hash) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid(),id,await hash(raw),csrfToken,created,expires,created,req.headers.get('User-Agent')||'',await hash(ip(req))).run();return out({ok:true,csrfToken},200,{'set-cookie':sessionCookie(raw,DAYS*86400)})}
async function signup(req,env){if(!env.DB)return out({error:'Account service is not configured yet'},503);const b=await body(req),email=String(b?.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||typeof b?.password!=='string'||b.password.length<12||b.password.length>128)return out({error:'Use a valid email and a password of at least 12 characters'},400);if(!(await rate(env,`signup:${ip(req)}`,8)))return out({error:'Too many attempts. Try again later.'},429);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return out({error:'Account already exists'},409);const p=await pw(b.password),idv=uid(),z=t();await env.DB.prepare('INSERT INTO users(id,email,password_hash,password_salt,role,plan,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(idv,email,p.hash,p.salt,'user','free','active',z,z).run();return start(req,env,idv)}
async function login(req,env){if(!env.DB)return out({error:'Account service is not configured yet'},503);const b=await body(req),email=String(b?.email||'').trim().toLowerCase(),key=`login:${ip(req)}:${email}`;if(!(await rate(env,key)))return out({error:'Too many login attempts. Try again later.'},429);const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first(),p=u?await pw(String(b?.password||''),u.password_salt):null;if(!u||!p||p.hash!==u.password_hash){await attempt(env,key,true);return out({error:'Invalid credentials'},401)}if(u.status!=='active')return out({error:'Account is not active'},403);await attempt(env,key,false);await env.DB.prepare('UPDATE users SET last_login_at=?,updated_at=? WHERE id=?').bind(t(),t(),u.id).run();return start(req,env,u.id)}
async function logout(req,env){const raw=parseCookies(req).zt_session;if(env.DB&&raw)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(raw)).run();return out({ok:true},200,{'set-cookie':sessionCookie('',0)})}
async function me(req,env){const s=await sess(req,env);return s?out({authenticated:true,user:{id:s.user_id,email:s.email,role:s.role,plan:s.plan},csrfToken:s.csrf_token}):out({authenticated:false})}
async function bootstrap(req,env){if(!env.DB||!env.OWNER_EMAIL||!env.OWNER_BOOTSTRAP_SECRET)return out({error:'Owner bootstrap is not configured'},503);if(req.headers.get('x-owner-bootstrap')!==env.OWNER_BOOTSTRAP_SECRET)return out({error:'Unauthorized'},401);const b=await body(req),email=String(b?.email||'').trim().toLowerCase();if(email!==String(env.OWNER_EMAIL).trim().toLowerCase()||typeof b?.password!=='string'||b.password.length<12)return out({error:'Invalid bootstrap request'},400);const p=await pw(b.password),z=t(),u=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(u)await env.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,role='owner',plan='pro',status='active',updated_at=? WHERE id=?").bind(p.hash,p.salt,z,u.id).run();else await env.DB.prepare('INSERT INTO users(id,email,password_hash,password_salt,role,plan,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid(),email,p.hash,p.salt,'owner','pro','active',z,z).run();return out({ok:true})}
async function ov(req,env){const g=await owner(req,env);if(g.r)return g.r;const [a,b,c,d]=await Promise.all([env.DB.prepare("SELECT COUNT(*) n FROM users WHERE status='active'").first(),env.DB.prepare("SELECT COUNT(*) n FROM users WHERE plan='pro' AND status='active'").first(),env.DB.prepare("SELECT COUNT(*) n FROM users WHERE status='suspended'").first(),env.DB.prepare('SELECT COUNT(*) n FROM audit_log').first()]);return out({users:a?.n||0,pro:b?.n||0,suspended:c?.n||0,auditEntries:d?.n||0})}
async function users(req,env){const g=await owner(req,env);if(g.r)return g.r;return out({users:(await env.DB.prepare('SELECT id,email,role,plan,status,created_at,last_login_at FROM users ORDER BY created_at DESC LIMIT 200').all()).results||[]})}
async function logs(req,env){const g=await owner(req,env);if(g.r)return g.r;return out({entries:(await env.DB.prepare('SELECT a.id,a.action,a.target_type,a.target_id,a.metadata_json,a.created_at,u.email actor_email FROM audit_log a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.id DESC LIMIT 200').all()).results||[]})}
async function mutateUser(req,env,idv){const g=await owner(req,env);if(g.r)return g.r;if(!(await csrf(req,g.s)))return out({error:'CSRF validation failed'},403);const b=await body(req);if(b?.plan&&['free','pro'].includes(b.plan))await env.DB.prepare("UPDATE users SET plan=?,updated_at=? WHERE id=? AND role!='owner'").bind(b.plan,t(),idv).run();if(b?.status&&['active','suspended'].includes(b.status))await env.DB.prepare("UPDATE users SET status=?,updated_at=? WHERE id=? AND role!='owner'").bind(b.status,t(),idv).run();await audit(env,g.s,'owner.user.update','user',idv,b||{});return out({ok:true})}
async function tool(req,env,slug){const g=await owner(req,env);if(g.r)return g.r;if(!(await csrf(req,g.s)))return out({error:'CSRF validation failed'},403);const b=await body(req);if(!['free','pro'].includes(b?.requiredPlan)||typeof b.enabled!=='boolean')return out({error:'Invalid entitlement'},400);await env.DB.prepare('INSERT INTO tool_entitlements(slug,required_plan,enabled,updated_at,updated_by) VALUES(?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET required_plan=excluded.required_plan,enabled=excluded.enabled,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(slug,b.requiredPlan,b.enabled?1:0,t(),g.s.user_id).run();await audit(env,g.s,'owner.tool.entitlement','tool',slug,b);return out({ok:true})}
async function setting(req,env){const g=await owner(req,env);if(g.r)return g.r;if(!(await csrf(req,g.s)))return out({error:'CSRF validation failed'},403);const b=await body(req);if(typeof b?.key!=='string'||typeof b?.value!=='string'||b.key.length>80||b.value.length>5000)return out({error:'Invalid setting'},400);await env.DB.prepare('INSERT INTO settings(key,value,updated_at,updated_by) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(b.key,b.value,t(),g.s.user_id).run();await audit(env,g.s,'owner.setting.update','setting',b.key);return out({ok:true})}
async function announcement(req,env){const g=await owner(req,env);if(g.r)return g.r;if(!(await csrf(req,g.s)))return out({error:'CSRF validation failed'},403);const b=await body(req);if(!b?.title||!b?.body||String(b.title).length>160||String(b.body).length>5000)return out({error:'Invalid announcement'},400);const z=t();await env.DB.prepare('INSERT INTO announcements(title,body,enabled,created_at,updated_at,created_by) VALUES(?,?,1,?,?,?)').bind(String(b.title),String(b.body),z,z,g.s.user_id).run();await audit(env,g.s,'owner.announcement.create','announcement','new',{title:b.title});return out({ok:true})}
async function entitlement(req,env,slug){const s=await sess(req,env),e=env.DB?await env.DB.prepare('SELECT required_plan,enabled FROM tool_entitlements WHERE slug=?').bind(slug).first():null;if(e&&!e.enabled)return out({allowed:false,reason:'disabled'},403);if(e?.required_plan==='pro'&&s?.plan!=='pro')return out({allowed:false,reason:'pro_required'},403);return out({allowed:true,plan:s?.plan||'free',authenticated:!!s})}
async function route(req,env){const p=new URL(req.url).pathname.replace(/^\/Zero-trust/,'');if(p==='/api/health')return out({ok:true,service:'zero-trust-api',database:!!env.DB});if(p==='/api/me'&&req.method==='GET')return me(req,env);if(p==='/api/auth/signup'&&req.method==='POST')return signup(req,env);if(p==='/api/auth/login'&&req.method==='POST')return login(req,env);if(p==='/api/auth/logout'&&req.method==='POST')return logout(req,env);if(p==='/api/owner/bootstrap'&&req.method==='POST')return bootstrap(req,env);if(p==='/api/owner/overview'&&req.method==='GET')return ov(req,env);if(p==='/api/owner/users'&&req.method==='GET')return users(req,env);if(p==='/api/owner/audit'&&req.method==='GET')return logs(req,env);if(p.startsWith('/api/owner/users/')&&req.method==='PATCH')return mutateUser(req,env,p.split('/').pop());if(p.startsWith('/api/owner/tools/')&&req.method==='POST')return tool(req,env,p.slice('/api/owner/tools/'.length));if(p==='/api/owner/settings'&&req.method==='POST')return setting(req,env);if(p==='/api/owner/announcements'&&req.method==='POST')return announcement(req,env);if(p.startsWith('/api/tools/')&&req.method==='GET')return entitlement(req,env,p.slice('/api/tools/'.length));return null}
export default{async fetch(req,env){try{const r=await route(req,env);if(r){const h=new Headers(r.headers);Object.entries(headers()).forEach(([k,v])=>h.set(k,v));return new Response(r.body,{status:r.status,headers:h})}return env.ASSETS.fetch(req)}catch(e){console.error(e);return out({error:'Internal server error'},500,headers())}}};
