const SESSION_DAYS = 7;
const PBKDF2_ITERATIONS = 210000;
const json = (data, status = 200, headers = {}) => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...headers } });
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const bytes = n => crypto.getRandomValues(new Uint8Array(n));
const b64 = a => btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const fromB64 = s => Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/') + '='.repeat((4-s.length%4)%4)), c=>c.charCodeAt(0));
async function sha256(text){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))))}
async function passwordHash(password, saltB64){const salt=saltB64?fromB64(saltB64):bytes(16);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:PBKDF2_ITERATIONS,hash:'SHA-256'},key,256);return {salt:b64(salt),hash:b64(new Uint8Array(bits))}}
const cookie = (name,value,maxAge) => `${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Strict`;
function cookies(req){return Object.fromEntries((req.headers.get('Cookie')||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function secureHeaders(){return {'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy':'same-origin','content-security-policy':"default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'"}}
function clientKey(req){return req.headers.get('CF-Connecting-IP')||'unknown'}
async function rateLimit(env,key,limit=12,windowMs=15*60*1000){if(!env.DB)return true;const t=Date.now(),row=await env.DB.prepare('SELECT * FROM login_attempts WHERE key=?').bind(key).first();if(!row||t-Date.parse(row.window_started_at)>windowMs){await env.DB.prepare('INSERT OR REPLACE INTO login_attempts(key,window_started_at,attempts,blocked_until) VALUES(?,?,0,NULL)').bind(key,new Date(t).toISOString()).run();return true}if(row.blocked_until&&Date.parse(row.blocked_until)>t)return false;return row.attempts<limit}
async function noteAttempt(env,key,failed){if(!env.DB)return;if(!failed){await env.DB.prepare('DELETE FROM login_attempts WHERE key=?').bind(key).run();return}const t=now(),row=await env.DB.prepare('SELECT * FROM login_attempts WHERE key=?').bind(key).first();const attempts=(row?.attempts||0)+1;const blocked=attempts>=12?new Date(Date.now()+30*60*1000).toISOString():null;await env.DB.prepare('INSERT OR REPLACE INTO login_attempts(key,window_started_at,attempts,blocked_until) VALUES(?,?,?,?)').bind(key,row?.window_started_at||t,attempts,blocked).run()}
async function session(req,env){if(!env.DB)return null;const c=cookies(req),raw=c.zt_session;if(!raw)return null;const token=await sha256(raw),r=await env.DB.prepare(`SELECT s.*,u.email,u.role,u.plan,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(token,now()).first();if(!r||r.status!=='active')return null;return r}
async function requireSession(req,env){const s=await session(req,env);return s||json({error:'Authentication required'},401)}
async function requireOwner(req,env){const s=await session(req,env);if(!s)return {response:json({error:'Authentication required'},401)};if(s.role!=='owner')return {response:json({error:'Owner access required'},403)};return {session:s}}
async function csrf(req,s){const token=req.headers.get('x-csrf-token');return !!token&&token===s.csrf_token}
async function audit(env,s,action,targetType='',targetId='',metadata={}){if(!env.DB||!s)return;await env.DB.prepare('INSERT INTO audit_log(actor_user_id,action,target_type,target_id,metadata_json,created_at,ip_hash) VALUES(?,?,?,?,?,?,?)').bind(s.user_id,action,targetType,targetId,JSON.stringify(metadata),now(),await sha256(clientKey({headers:new Headers({'CF-Connecting-IP':clientKey})}))).run().catch(()=>{})}
async function body(req){try{return await req.json()}catch{return null}}
function validEmail(e){return typeof e==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&e.length<=254}
function validPassword(p){return typeof p==='string'&&p.length>=12&&p.length<=128}
async function signup(req,env){if(!env.DB)return json({error:'Account service is not configured yet'},503);const b=await body(req);if(!validEmail(b?.email)||!validPassword(b?.password))return json({error:'Use a valid email and a password of at least 12 characters'},400);const email=b.email.trim().toLowerCase();if(!(await rateLimit(env,`signup:${clientKey(req)}`,8)))return json({error:'Too many attempts. Try again later.'},429);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'Account already exists'},409);const ph=await passwordHash(b.password),uid=id(),t=now();await env.DB.prepare('INSERT INTO users(id,email,password_hash,password_salt,role,plan,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid,email,ph.hash,ph.salt,'user','free','active',t,t).run();return await startSession(req,env,uid)}
async function startSession(req,env,uid){const raw=b64(bytes(32)),csrfToken=b64(bytes(24)),t=now(),exp=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,csrf_token,created_at,expires_at,last_seen_at,user_agent,ip_hash) VALUES(?,?,?,?,?,?,?,?,?)').bind(id(),uid,await sha256(raw),csrfToken,t,exp,t,req.headers.get('User-Agent')||'',await sha256(clientKey(req))).run();return json({ok:true,csrfToken},{headers:{'set-cookie':cookie('zt_session',raw,SESSION_DAYS*86400)}})}
async function login(req,env){if(!env.DB)return json({error:'Account service is not configured yet'},503);const b=await body(req);if(!validEmail(b?.email)||typeof b?.password!=='string')return json({error:'Invalid credentials'},400);const key=`login:${clientKey(req)}:${b.email.trim().toLowerCase()}`;if(!(await rateLimit(env,key)))return json({error:'Too many login attempts. Try again later.'},429);const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(b.email.trim().toLowerCase()).first();const check=u?await passwordHash(b.password,u.password_salt):null;if(!u||!check||check.hash!==u.password_hash){await noteAttempt(env,key,true);return json({error:'Invalid credentials'},401)}if(u.status!=='active')return json({error:'Account is not active'},403);await noteAttempt(env,key,false);await env.DB.prepare('UPDATE users SET last_login_at=?,updated_at=? WHERE id=?').bind(now(),now(),u.id).run();return await startSession(req,env,u.id)}
async function logout(req,env){const c=cookies(req),raw=c.zt_session;if(env.DB&&raw)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(raw)).run();return json({ok:true},{headers:{'set-cookie':cookie('zt_session','',0)}})}
async function me(req,env){const s=await session(req,env);if(!s)return json({authenticated:false});return json({authenticated:true,user:{id:s.user_id,email:s.email,role:s.role,plan:s.plan},csrfToken:s.csrf_token})}
async function ownerBootstrap(req,env){if(!env.DB||!env.OWNER_EMAIL||!env.OWNER_BOOTSTRAP_SECRET)return json({error:'Owner bootstrap is not configured'},503);const secret=req.headers.get('x-owner-bootstrap');if(!secret||secret!==env.OWNER_BOOTSTRAP_SECRET)return json({error:'Unauthorized'},401);const b=await body(req);if(!validEmail(b?.email)||b.email.trim().toLowerCase()!==env.OWNER_EMAIL.trim().toLowerCase()||!validPassword(b?.password))return json({error:'Invalid bootstrap request'},400);const email=env.OWNER_EMAIL.trim().toLowerCase(),ph=await passwordHash(b.password),t=now(),existing=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(existing)await env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,role=\'owner\',plan=\'pro\',status=\'active\',updated_at=? WHERE id=?').bind(ph.hash,ph.salt,t,existing.id).run();else await env.DB.prepare('INSERT INTO users(id,email,password_hash,password_salt,role,plan,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id(),email,ph.hash,ph.salt,'owner','pro','active',t,t).run();return json({ok:true,message:'Owner account provisioned. Remove the bootstrap secret after first use.'})}
async function ownerOverview(req,env){const gate=await requireOwner(req,env);if(gate.response)return gate.response;if(!env.DB)return json({error:'Database unavailable'},503);const [users,pro,suspended,auditRows,settings,ann]=await Promise.all([env.DB.prepare("SELECT COUNT(*) n FROM users WHERE status='active'").first(),env.DB.prepare("SELECT COUNT(*) n FROM users WHERE plan='pro' AND status='active'").first(),env.DB.prepare("SELECT COUNT(*) n FROM users WHERE status='suspended'").first(),env.DB.prepare('SELECT COUNT(*) n FROM audit_log').first(),env.DB.prepare('SELECT key,value,updated_at FROM settings').all(),env.DB.prepare('SELECT id,title,body,enabled,created_at,updated_at FROM announcements ORDER BY id DESC LIMIT 10').all()]);return json({users:users?.n||0,pro:pro?.n||0,suspended:suspended?.n||0,auditEntries:auditRows?.n||0,settings:settings.results||[],announcements:ann.results||[]})}
async function ownerUsers(req,env){const gate=await requireOwner(req,env);if(gate.response)return gate.response;const rows=await env.DB.prepare('SELECT id,email,role,plan,status,created_at,last_login_at FROM users ORDER BY created_at DESC LIMIT 200').all();return json({users:rows.results||[]})}
async function ownerAudit(req,env){const gate=await requireOwner(req,env);if(gate.response)return gate.response;const rows=await env.DB.prepare('SELECT a.id,a.action,a.target_type,a.target_id,a.metadata_json,a.created_at,u.email actor_email FROM audit_log a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.id DESC LIMIT 200').all();return json({entries:rows.results||[]})}
async function ownerUserAction(req,env,idParam){const gate=await requireOwner(req,env);if(gate.response)return gate.response;if(!await csrf(req,gate.session))return json({error:'CSRF validation failed'},403);const b=await body(req);if(!['active','suspended'].includes(b?.status)&&!['free','pro'].includes(b?.plan))return json({error:'Invalid user update'},400);if(b.status==='active'||b.status==='suspended')await env.DB.prepare('UPDATE users SET status=?,updated_at=? WHERE id=? AND role!=\'owner\'').bind(b.status,now(),idParam).run();if(b.plan==='free'||b.plan==='pro')await env.DB.prepare('UPDATE users SET plan=?,updated_at=? WHERE id=? AND role!=\'owner\'').bind(b.plan,now(),idParam).run();await audit(env,gate.session,'owner.user.update','user',idParam,b);return json({ok:true})}
async function ownerTool(req,env,slug){const gate=await requireOwner(req,env);if(gate.response)return gate.response;if(!await csrf(req,gate.session))return json({error:'CSRF validation failed'},403);const b=await body(req);if(!['free','pro'].includes(b?.requiredPlan)||typeof b.enabled!=='boolean')return json({error:'Invalid entitlement'},400);await env.DB.prepare('INSERT INTO tool_entitlements(slug,required_plan,enabled,updated_at,updated_by) VALUES(?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET required_plan=excluded.required_plan,enabled=excluded.enabled,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(slug,b.requiredPlan,b.enabled?1:0,now(),gate.session.user_id).run();await audit(env,gate.session,'owner.tool.entitlement','tool',slug,b);return json({ok:true})}
async function entitlement(req,env,slug){const s=await session(req,env);const row=env.DB?await env.DB.prepare('SELECT required_plan,enabled FROM tool_entitlements WHERE slug=?').bind(slug).first():null;if(row&&!row.enabled)return json({allowed:false,reason:'disabled'},403);if(row?.required_plan==='pro'&&s?.plan!=='pro')return json({allowed:false,reason:'pro_required'},403);return json({allowed:true,plan:s?.plan||'free'})}
async function ownerSetting(req,env){const gate=await requireOwner(req,env);if(gate.response)return gate.response;if(!await csrf(req,gate.session))return json({error:'CSRF validation failed'},403);const b=await body(req);if(typeof b?.key!=='string'||b.key.length>80||typeof b.value!=='string'||b.value.length>5000)return json({error:'Invalid setting'},400);await env.DB.prepare('INSERT INTO settings(key,value,updated_at,updated_by) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(b.key,b.value,now(),gate.session.user_id).run();await audit(env,gate.session,'owner.setting.update','setting',b.key);return json({ok:true})}
async function ownerAnnouncement(req,env){const gate=await requireOwner(req,env);if(gate.response)return gate.response;if(!await csrf(req,gate.session))return json({error:'CSRF validation failed'},403);const b=await body(req);if(!b?.title||!b?.body||String(b.title).length>160||String(b.body).length>5000)return json({error:'Invalid announcement'},400);const t=now();await env.DB.prepare('INSERT INTO announcements(title,body,enabled,created_at,updated_at,created_by) VALUES(?,?,1,?,?,?)').bind(String(b.title),String(b.body),t,t,gate.session.user_id).run();await audit(env,gate.session,'owner.announcement.create','announcement','new',{title:b.title});return json({ok:true})}
async function usage(req,env,slug){const s=await session(req,env);if(!s)return json({allowed:true,plan:'free',authenticated:false});if(!env.DB)return json({allowed:true,plan:s.plan,authenticated:true});const e=await env.DB.prepare('SELECT required_plan,enabled FROM tool_entitlements WHERE slug=?').bind(slug).first();if(e&&!e.enabled)return json({allowed:false,reason:'disabled'},403);if(e?.required_plan==='pro'&&s.plan!=='pro')return json({allowed:false,reason:'pro_required'},403);return json({allowed:true,plan:s.plan,authenticated:true})}
async function route(req,env){const u=new URL(req.url),p=u.pathname.replace(/^\/Zero-trust/,'');if(p==='/api/health')return json({ok:true,service:'zero-trust-api',database:!!env.DB});if(p==='/api/me'&&req.method==='GET')return me(req,env);if(p==='/api/auth/signup'&&req.method==='POST')return signup(req,env);if(p==='/api/auth/login'&&req.method==='POST')return login(req,env);if(p==='/api/auth/logout'&&req.method==='POST')return logout(req,env);if(p==='/api/owner/bootstrap'&&req.method==='POST')return ownerBootstrap(req,env);if(p==='/api/owner/overview'&&req.method==='GET')return ownerOverview(req,env);if(p==='/api/owner/users'&&req.method==='GET')return ownerUsers(req,env);if(p==='/api/owner/audit'&&req.method==='GET')return ownerAudit(req,env);if(p.startsWith('/api/owner/users/')&&req.method==='PATCH')return ownerUserAction(req,env,p.split('/').pop());if(p.startsWith('/api/owner/tools/')&&req.method==='POST')return ownerTool(req,env,p.slice('/api/owner/tools/'.length));if(p==='/api/owner/settings'&&req.method==='POST')return ownerSetting(req,env);if(p==='/api/owner/announcements'&&req.method==='POST')return ownerAnnouncement(req,env);if(p.startsWith('/api/tools/')&&req.method==='GET')return usage(req,env,p.slice('/api/tools/'.length));return null}
export default {async fetch(req,env){try{const r=await route(req,env);if(r){const h=new Headers(r.headers);for(const[k,v]of Object.entries(secureHeaders()))h.set(k,v);return new Response(r.body,{status:r.status,headers:h})}return env.ASSETS.fetch(req)}catch(e){console.error(e);return json({error:'Internal server error'},500,secureHeaders())}}};
